<table width="100%">
	<tr>
    <td height='1' bgColor='#666666'>
    </td>
  </tr>
	<tr>
		<td height="40" align="center" valign="middle" class="footer">This application was built using <A href="http://www.fusioncharts.com" target="_blank"><strong>FusionCharts XT</strong></A> &amp; <a href="http://www.fusioncharts.com/maps" target="_blank"><strong>FusionMaps XT</strong></a>. <br>
		&copy; All Rights Reserved - InfoSoft Global (P) Ltd. 
		</td>
	</tr>
</table>