<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="230" height="78" align="center" valign="top"><a href='http://www.infosoftglobal.com' target='_blank'><img src="../../images/logo.jpg" border='0' width="212" height="78" alt='InfoSoft Global (P) Ltd.'></a></td>
    <td align="right" valign="bottom"><a href='http://www.fusioncharts.com/maps' target='_blank'><img src="../../images/FMLogo.jpg" border='0' alt='FusionMaps'></a>&nbsp;</td>
  </tr>
  <tr>
    <td height='5' colspan='2'>
    </td>
  </tr>
  <tr>
    <td colspan='2' height='1' bgColor='#666666'>
    </td>
  </tr>
</table>