function getMapList() {
	var mapList = [];
	mapList.push({isMap:false,title:"Please select a map below",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"------------------------------------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"World",swf:"FCMap_World.swf",width:715,height:405});
	mapList.push({isMap:true,title:"World 8 Regions",swf:"FCMap_World8.swf",width:715,height:405});
	mapList.push({isMap:true,title:"World with countries",swf:"FCMap_WorldwithCountries.swf",width:2160,height:1130});
	mapList.push({isMap:true,title:"World with Antarctica",swf:"FCMap_WorldWithAntarctica.swf",width:879,height:500});
	mapList.push({isMap:true,title:"World 8 Regions with Antarctica Map",swf:"FCMap_World8WithAntarctica.swf",width:895,height:498});
	mapList.push({isMap:true,title:"Europe",swf:"FCMap_Europe.swf",width:620,height:600});
	mapList.push({isMap:true,title:"North America",swf:"FCMap_NorthAmerica.swf",width:675,height:675});
	mapList.push({isMap:true,title:"Central America",swf:"FCMap_CentralAmerica.swf",width:610,height:470});
	mapList.push({isMap:true,title:"South America",swf:"FCMap_SouthAmerica.swf",width:600,height:700});
	mapList.push({isMap:true,title:"Asia",swf:"FCMap_Asia.swf",width:650,height:650});
	mapList.push({isMap:true,title:"Africa",swf:"FCMap_Africa.swf",width:670,height:620});
	mapList.push({isMap:true,title:"Middle East",swf:"FCMap_MiddleEast.swf",width:620,height:480});
	mapList.push({isMap:true,title:"Oceania",swf:"FCMap_Oceania.swf",width:675,height:525});
	mapList.push({isMap:true,title:"Asia (No Mid-east)",swf:"FCMap_Asia3.swf",width:650,height:650});
	mapList.push({isMap:true,title:"North America (no Central)",swf:"FCMap_NorthAmericaWOCentral.swf",width:660,height:660});	
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"--------- US & Counties ---------",swf:"",width:0,height:0});
	
	mapList.push({isMap:true,title:"USA (States)",swf:"FCMap_USA.swf",width:750,height:460});
	mapList.push({isMap:true,title:"Alaska",swf:"FCMap_Alaska.swf",width:685,height:555});
	mapList.push({isMap:true,title:"Alabama",swf:"FCMap_Alabama.swf",width:575,height:875});
	mapList.push({isMap:true,title:"Arizona",swf:"FCMap_Arizona.swf",width:600,height:690});
	mapList.push({isMap:true,title:"Arkansas",swf:"FCMap_Arkansas.swf",width:720,height:650});
	mapList.push({isMap:true,title:"California",swf:"FCMap_California.swf",width:620,height:705});
	mapList.push({isMap:true,title:"Colorado",swf:"FCMap_Colorado.swf",width:810,height:670});
	mapList.push({isMap:true,title:"Connecticut",swf:"FCMap_Connecticut.swf",width:760,height:570});
	mapList.push({isMap:true,title:"Delaware",swf:"FCMap_Delaware.swf",width:375,height:850});
	mapList.push({isMap:true,title:"District of Columbia",swf:"FCMap_DistrictofColumbia.swf",width:640,height:750});
	mapList.push({isMap:true,title:"Florida",swf:"FCMap_Florida.swf",width:650,height:600});
	mapList.push({isMap:true,title:"Georgia",swf:"FCMap_Georgia.swf",width:610,height:700});
	mapList.push({isMap:true,title:"Hawaii",swf:"FCMap_Hawaii.swf",width:770,height:490});
	mapList.push({isMap:true,title:"Idaho",swf:"FCMap_Idaho.swf",width:575,height:900});
	mapList.push({isMap:true,title:"Illinois",swf:"FCMap_Illinois.swf",width:550,height:910});
	mapList.push({isMap:true,title:"Indiana",swf:"FCMap_Indiana.swf",width:580,height:890});
	mapList.push({isMap:true,title:"Iowa",swf:"FCMap_Iowa.swf",width:760,height:500});
	mapList.push({isMap:true,title:"Kentucky",swf:"FCMap_Kentucky.swf",width:910,height:430});
	mapList.push({isMap:true,title:"Kansas",swf:"FCMap_Kansas.swf",width:760,height:400});
	mapList.push({isMap:true,title:"Lousiana",swf:"FCMap_Louisiana.swf",width:710,height:610});
	mapList.push({isMap:true,title:"Maine",swf:"FCMap_Maine.swf",width:600,height:870});
	mapList.push({isMap:true,title:"Maryland",swf:"FCMap_Maryland.swf",width:750,height:400});
	mapList.push({isMap:true,title:"Massachusetts",swf:"FCMap_Massachusetts.swf",width:770,height:490});
	mapList.push({isMap:true,title:"Michigan",swf:"FCMap_Michigan.swf",width:600,height:700});
	mapList.push({isMap:true,title:"Minnesota",swf:"FCMap_Minnesota.swf",width:620,height:670});
	mapList.push({isMap:true,title:"Mississippi",swf:"FCMap_Mississippi.swf",width:570,height:900});
	mapList.push({isMap:true,title:"Missouri",swf:"FCMap_Missouri.swf",width:680,height:600});
	mapList.push({isMap:true,title:"Montana",swf:"FCMap_Montana.swf",width:775,height:450});
	mapList.push({isMap:true,title:"Nebraska",swf:"FCMap_Nebraska.swf",width:775,height:375});
	mapList.push({isMap:true,title:"Nevada",swf:"FCMap_Nevada.swf",width:630,height:880});
	mapList.push({isMap:true,title:"New Hampshire",swf:"FCMap_NewHampshire.swf",width:300,height:550});
	mapList.push({isMap:true,title:"New Jersey",swf:"FCMap_NewJersey.swf",width:485,height:890});
	mapList.push({isMap:true,title:"New Mexico",swf:"FCMap_NewMexico.swf",width:600,height:690});
	mapList.push({isMap:true,title:"New York",swf:"FCMap_NewYork.swf",width:775,height:600});
	mapList.push({isMap:true,title:"North Carolina",swf:"FCMap_NorthCarolina.swf",width:900,height:400});
	mapList.push({isMap:true,title:"North Dakota",swf:"FCMap_NorthDakota.swf",width:770,height:470});
	mapList.push({isMap:true,title:"Ohio",swf:"FCMap_Ohio.swf",width:620,height:670});
	mapList.push({isMap:true,title:"Oklahoma",swf:"FCMap_Oklahoma.swf",width:780,height:380});
	mapList.push({isMap:true,title:"Oregon",swf:"FCMap_Oregon.swf",width:760,height:570});
	mapList.push({isMap:true,title:"Pennsylvania",swf:"FCMap_Pennsylvania.swf",width:770,height:460});
	mapList.push({isMap:true,title:"Rhode Island",swf:"FCMap_RhodeIsland.swf",width:600,height:900});
	mapList.push({isMap:true,title:"South Carolina",swf:"FCMap_SouthCarolina.swf",width:760,height:550});
	mapList.push({isMap:true,title:"South Dakota",swf:"FCMap_SouthDakota.swf",width:770,height:500});
	mapList.push({isMap:true,title:"Tennessee",swf:"FCMap_Tennessee.swf",width:770,height:210});
	mapList.push({isMap:true,title:"Texas",swf:"FCMap_Texas.swf",width:980,height:920});
	mapList.push({isMap:true,title:"Utah",swf:"FCMap_Utah.swf",width:620,height:780});
	mapList.push({isMap:true,title:"Washington",swf:"FCMap_Washington.swf",width:780,height:520});
	mapList.push({isMap:true,title:"Vermont",swf:"FCMap_Vermont.swf",width:570,height:900});
	mapList.push({isMap:true,title:"Virginia",swf:"FCMap_Virginia.swf",width:890,height:490});
	mapList.push({isMap:true,title:"West Virginia",swf:"FCMap_WestVirginia.swf",width:710,height:610});
	mapList.push({isMap:true,title:"Wisconsin",swf:"FCMap_Wisconsin.swf",width:650,height:690});
	mapList.push({isMap:true,title:"Wyoming",swf:"FCMap_Wyoming.swf",width:710,height:610});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"----------- US Regions ----------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"USA (All Regions)",swf:"FCMap_USARegion.swf",width:710,height:510});
	mapList.push({isMap:true,title:"USA North East Region",swf:"FCMap_USANorthEastRegion.swf",width:440,height:400});
	mapList.push({isMap:true,title:"USA North West Region",swf:"FCMap_USANorthWestRegion.swf",width:360,height:320});
	mapList.push({isMap:true,title:"USA Central Region",swf:"FCMap_USACentralRegion.swf",width:250,height:350});
	mapList.push({isMap:true,title:"USA South East Region",swf:"FCMap_USASouthEastRegion.swf",width:460,height:360});
	mapList.push({isMap:true,title:"USA South West Region",swf:"FCMap_USASouthWestRegion.swf",width:270,height:230});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"------- Europe & Countries ------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"Europe (All Countries)",swf:"FCMap_EuropewithCountries.swf",width:620,height:600});	
	mapList.push({isMap:true,title:"Europe (With all islands)",swf:"FCMap_Europe2.swf",width:460,height:460});	
	mapList.push({isMap:true,title:"Albania",swf:"FCMap_Albania.swf",width:190,height:410});
	mapList.push({isMap:true,title:"Andorra",swf:"FCMap_Andorra.swf",width:490,height:400});
	mapList.push({isMap:true,title:"Austria",swf:"FCMap_Austria.swf",width:580,height:320});
	mapList.push({isMap:true,title:"Belarus",swf:"FCMap_Belarus.swf",width:320,height:260});
	mapList.push({isMap:true,title:"Belgium",swf:"FCMap_Belgium.swf",width:400,height:330});
	mapList.push({isMap:true,title:"Bosnia-Herzegovina",swf:"FCMap_BosniaHerzegovina.swf",width:490,height:470});
	mapList.push({isMap:true,title:"Bulgaria",swf:"FCMap_Bulgaria.swf",width:580,height:400});
	mapList.push({isMap:true,title:"Croatia",swf:"FCMap_Croatia.swf",width:520,height:520});
	mapList.push({isMap:true,title:"Cyprus",swf:"FCMap_Cyprus.swf",width:630,height:390});
	mapList.push({isMap:true,title:"Cyprus (Regions)",swf:"FCMap_Cyprus2.swf",width:630,height:400});
	mapList.push({isMap:true,title:"Czech Republic",swf:"FCMap_CzechRepublic.swf",width:810,height:470});
	mapList.push({isMap:true,title:"Denmark",swf:"FCMap_Denmark.swf",width:700,height:550});
	mapList.push({isMap:true,title:"Denmark (Regions)",swf:"FCMap_DenmarkRegion.swf",width:530,height:590});
	mapList.push({isMap:true,title:"England",swf:"FCMap_England.swf",width:500,height:600});
	mapList.push({isMap:true,title:"Estonia",swf:"FCMap_Estonia.swf",width:600,height:400});
	mapList.push({isMap:true,title:"Finland",swf:"FCMap_Finland.swf",width:280,height:470});
	mapList.push({isMap:true,title:"France",swf:"FCMap_France.swf",width:650,height:575});
	mapList.push({isMap:true,title:"France (Departments)",swf:"FCMap_FranceDepartment.swf",width:620,height:580});
	mapList.push({isMap:true,title:"Germany",swf:"FCMap_Germany.swf",width:475,height:600});
	mapList.push({isMap:true,title:"Greece",swf:"FCMap_Greece.swf",width:420,height:430});
	mapList.push({isMap:true,title:"Hungary",swf:"FCMap_Hungary.swf",width:520,height:340});
	mapList.push({isMap:true,title:"Hungary (Regions)",swf:"FCMap_HungaryRegions.swf",width:780,height:500});
	mapList.push({isMap:true,title:"Iceland",swf:"FCMap_Iceland.swf",width:510,height:360});
	mapList.push({isMap:true,title:"Ireland",swf:"FCMap_Ireland.swf",width:425,height:550});
	mapList.push({isMap:true,title:"Italy",swf:"FCMap_Italy.swf",width:500,height:575});
	mapList.push({isMap:true,title:"Latvia",swf:"FCMap_Latvia.swf",width:530,height:320});
	mapList.push({isMap:true,title:"Liechtenstein",swf:"FCMap_Liechtenstein.swf",width:320,height:610});
	mapList.push({isMap:true,title:"Lithuania",swf:"FCMap_Lithuania.swf",width:800,height:620});
	mapList.push({isMap:true,title:"Luxembourg",swf:"FCMap_Luxembourg.swf",width:560,height:780});
	mapList.push({isMap:true,title:"Macedonia",swf:"FCMap_Macedonia.swf",width:520,height:430});
	mapList.push({isMap:true,title:"Malta",swf:"FCMap_Malta.swf",width:360,height:310});	
	mapList.push({isMap:true,title:"Moldova",swf:"FCMap_Moldova.swf",width:350,height:440});
	mapList.push({isMap:true,title:"Monaco",swf:"FCMap_Monaco.swf",width:270,height:360});
	mapList.push({isMap:true,title:"Montenegro",swf:"FCMap_Montenegro.swf",width:520,height:590});
	mapList.push({isMap:true,title:"Netherlands",swf:"FCMap_Netherlands.swf",width:500,height:575});
	mapList.push({isMap:true,title:"Norway",swf:"FCMap_Norway.swf",width:530,height:570});
	mapList.push({isMap:true,title:"Norway (Regions)",swf:"FCMap_NorwayRegion.swf",width:600,height:550});
	mapList.push({isMap:true,title:"Poland (Counties)",swf:"FCMap_PolandCounties.swf",width:730,height:680});
	mapList.push({isMap:true,title:"Poland",swf:"FCMap_Poland.swf",width:420,height:400});
	mapList.push({isMap:true,title:"Portugal",swf:"FCMap_Portugal.swf",width:260,height:520});
	mapList.push({isMap:true,title:"Romania",swf:"FCMap_Romania.swf",width:480,height:350});
	mapList.push({isMap:true,title:"San Marino",swf:"FCMap_SanMarino.swf",width:330,height:400});
	mapList.push({isMap:true,title:"Scotland",swf:"FCMap_Scotland.swf",width:575,height:575});
	mapList.push({isMap:true,title:"Serbia",swf:"FCMap_Serbia.swf",width:360,height:500});
	mapList.push({isMap:true,title:"Serbia(W/o Kosovo)",swf:"FCMap_SerbiaWoKosovo.swf",width:365,height:490});
	mapList.push({isMap:true,title:"Kosovo",swf:"FCMap_KosovoDistricts.swf",width:550,height:600});
	mapList.push({isMap:true,title:"Slovakia",swf:"FCMap_Slovakia.swf",width:620,height:320});
	mapList.push({isMap:true,title:"Slovenia",swf:"FCMap_Slovenia.swf",width:570,height:390});
	mapList.push({isMap:true,title:"Spain (Autonomous)",swf:"FCMap_Spain.swf",width:560,height:400});
	mapList.push({isMap:true,title:"Spain (Provinces)",swf:"FCMap_SpainProvinces.swf",width:820,height:580});
	mapList.push({isMap:true,title:"Sweden",swf:"FCMap_Sweden.swf",width:300,height:600});
	mapList.push({isMap:true,title:"Switzerland",swf:"FCMap_Switzerland.swf",width:520,height:350});
	mapList.push({isMap:true,title:"Turkey",swf:"FCMap_Turkey.swf",width:720,height:330});
	mapList.push({isMap:true,title:"UK",swf:"FCMap_UK.swf",width:270,height:430});
	mapList.push({isMap:true,title:"Ukraine",swf:"FCMap_Ukraine.swf",width:560,height:390});
	mapList.push({isMap:true,title:"Vatican City",swf:"FCMap_VaticanCity.swf",width:330,height:260});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"------- Europe By Regions ------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"Europe (All Regions)",swf:"FCMap_EuropeRegion.swf",width:440,height:410});
	mapList.push({isMap:true,title:"East European Region",swf:"FCMap_EastEuropeanRegion.swf",width:220,height:320});
	mapList.push({isMap:true,title:"West European Region",swf:"FCMap_WestEuropeanRegion.swf",width:280,height:320});
	mapList.push({isMap:true,title:"Central European Region",swf:"FCMap_CentralEuropeanRegion.swf",width:300,height:260});
	mapList.push({isMap:true,title:"North European Region",swf:"FCMap_NorthEuropeanRegion.swf",width:280,height:260});
	mapList.push({isMap:true,title:"South European Region",swf:"FCMap_SouthEuropeanRegion.swf",width:600,height:225});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"---------------- UK ----------------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"UK (With Islands)",swf:"FCMap_UK7.swf",width:360,height:590});
	mapList.push({isMap:true,title:"England (Region)",swf:"FCMap_EnglandRegion.swf",width:410,height:470});	
	mapList.push({isMap:true,title:"Scotland (Region)",swf:"FCMap_ScotlandRegion.swf",width:400,height:470});
	mapList.push({isMap:true,title:"Wales",swf:"FCMap_Wales.swf",width:340,height:410});	
	mapList.push({isMap:true,title:"Northern Ireland",swf:"FCMap_NorthernIreland.swf",width:420,height:350});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"--------- North America ---------",swf:"",width:0,height:0});	
	mapList.push({isMap:true,title:"Antigua",swf:"FCMap_Antigua.swf",width:510,height:380});
	mapList.push({isMap:true,title:"Bahamas",swf:"FCMap_Bahamas.swf",width:530,height:570});
	mapList.push({isMap:true,title:"Barbados",swf:"FCMap_Barbados.swf",width:210,height:270});	
	mapList.push({isMap:true,title:"British Columbia",swf:"FCMap_BritishColumbia.swf",width:570,height:530});
	mapList.push({isMap:true,title:"Canada",swf:"FCMap_Canada.swf",width:660,height:560});
	mapList.push({isMap:true,title:"CaymanIsland",swf:"FCMap_CaymanIslands.swf",width:920,height:450});
	mapList.push({isMap:true,title:"Cuba",swf:"FCMap_Cuba.swf",width:600,height:240});
	mapList.push({isMap:true,title:"Dominica",swf:"FCMap_Dominica.swf",width:160,height:280});
	mapList.push({isMap:true,title:"Dominican Republic",swf:"FCMap_DominicanRepublic.swf",width:410,height:300});
	mapList.push({isMap:true,title:"Greenland",swf:"FCMap_Greenland.swf",width:320,height:550});
	mapList.push({isMap:true,title:"Grenada",swf:"FCMap_Grenada.swf",width:260,height:300});
	mapList.push({isMap:true,title:"Haiti",swf:"FCMap_Haiti.swf",width:360,height:290});
	mapList.push({isMap:true,title:"Jamaica",swf:"FCMap_Jamaica.swf",width:420,height:180});
	mapList.push({isMap:true,title:"Mexico",swf:"FCMap_Mexico.swf",width:770,height:450});
	mapList.push({isMap:true,title:"Ontario",swf:"FCMap_Ontario.swf",width:615,height:600});
	mapList.push({isMap:true,title:"Puerto Rico",swf:"FCMap_PuertoRico.swf",width:670,height:350});
	mapList.push({isMap:true,title:"Quebec",swf:"FCMap_Quebec.swf",width:360,height:420});
	mapList.push({isMap:true,title:"Saint Kitts & Nevis",swf:"FCMap_SaintKittsandNevis.swf",width:360,height:340});
	mapList.push({isMap:true,title:"Saint Lucia",swf:"FCMap_SaintLucia.swf",width:280,height:530});
	mapList.push({isMap:true,title:"Saint Vincent & The Grenadines",swf:"FCMap_SaintVincentandtheGrenadines.swf",width:240,height:530});
	mapList.push({isMap:true,title:"Trinidad & Tabogo",swf:"FCMap_TrinidadandTobago.swf.swf",width:620,height:580});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"--------- South America ---------",swf:"",width:0,height:0});	
	mapList.push({isMap:true,title:"Argentina",swf:"FCMap_Argentina.swf",width:350,height:700});
	mapList.push({isMap:true,title:"Bolivia",swf:"FCMap_Bolivia.swf",width:310,height:350});
	mapList.push({isMap:true,title:"Brazil",swf:"FCMap_Brazil.swf",width:650,height:600});
	mapList.push({isMap:true,title:"Brazil (Regions)",swf:"FCMap_BrazilRegion.swf",width:380,height:380});
	mapList.push({isMap:true,title:"Chile",swf:"FCMap_Chile.swf",width:210,height:580});
	mapList.push({isMap:true,title:"Colombia",swf:"FCMap_Colombia.swf",width:430,height:580});
	mapList.push({isMap:true,title:"Ecuador",swf:"FCMap_Ecuador.swf",width:460,height:410});
	mapList.push({isMap:true,title:"Falkland Island",swf:"FCMap_FalklandIsland.swf",width:390,height:310});
	mapList.push({isMap:true,title:"French Guiana",swf:"FCMap_FrenchGuiana.swf",width:380,height:470});
	mapList.push({isMap:true,title:"Guyana",swf:"FCMap_Guyana.swf",width:340,height:420});
	mapList.push({isMap:true,title:"Paraguay",swf:"FCMap_Paraguay.swf",width:310,height:330});
	mapList.push({isMap:true,title:"Peru",swf:"FCMap_Peru.swf",width:370,height:520});
	mapList.push({isMap:true,title:"Suriname",swf:"FCMap_Suriname.swf",width:410,height:430});
	mapList.push({isMap:true,title:"Uruguay",swf:"FCMap_Uruguay.swf",width:310,height:350});
	mapList.push({isMap:true,title:"Venezuela",swf:"FCMap_Venezuela.swf",width:560,height:490});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"-------- Central America --------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"Central America (with Caribbean)",swf:"FCMap_CentralAmericawithCaribbean.swf",width:660,height:560});	
	mapList.push({isMap:true,title:"Central America (with Virgin Islands)",swf:"FCMap_CentralAmerica2.swf",width:660,height:660});
	mapList.push({isMap:true,title:"Belize",swf:"FCMap_Belize.swf",width:160,height:260});
	mapList.push({isMap:true,title:"Costa Rica",swf:"FCMap_CostaRica.swf",width:320,height:310});
	mapList.push({isMap:true,title:"El Salvador",swf:"FCMap_ElSalvador.swf",width:330,height:225});
	mapList.push({isMap:true,title:"Guatemala",swf:"FCMap_Guatemala.swf",width:450,height:450});	
	mapList.push({isMap:true,title:"Honduras",swf:"FCMap_Honduras.swf",width:420,height:260});
	mapList.push({isMap:true,title:"Nicaragua",swf:"FCMap_Nicaragua.swf",width:410,height:380});
	mapList.push({isMap:true,title:"Panama",swf:"FCMap_Panama.swf",width:430,height:210});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"-------- Canada - Provinces & Territories --------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"Alberta",swf:"FCMap_Alberta.swf",width:290,height:490});
	mapList.push({isMap:true,title:"Manitoba",swf:"FCMap_Manitoba.swf",width:330,height:480});
	mapList.push({isMap:true,title:"New Brunswick",swf:"FCMap_NewBrunswick.swf",width:460,height:460});
	mapList.push({isMap:true,title:"Newfoundland & Labrador",swf:"FCMap_NewfoundlandandLabrador.swf",width:450,height:350});
	mapList.push({isMap:true,title:"Northwest Territories",swf:"FCMap_NorthwestTerritories.swf",width:310,height:480});
	mapList.push({isMap:true,title:"Nova Scotia",swf:"FCMap_NovaScotia.swf",width:460,height:350});
	mapList.push({isMap:true,title:"Nunavut",swf:"FCMap_Nunavut.swf",width:360,height:450});
	mapList.push({isMap:true,title:"Prince Edward Island",swf:"FCMap_PrinceEdwardIsland.swf",width:470,height:320});
	mapList.push({isMap:true,title:"Saskatchewan",swf:"FCMap_Saskatchewan.swf",width:260,height:460});
	mapList.push({isMap:true,title:"Yukon Territory",swf:"FCMap_YukonTerritory.swf",width:510,height:750});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"--------------- Asia ---------------",swf:"",width:0,height:0});			
	mapList.push({isMap:true,title:"Armenia",swf:"FCMap_Armenia.swf",width:500,height:510});
	mapList.push({isMap:true,title:"Azerbaijan",swf:"FCMap_Azerbaijan.swf",width:600,height:480});
	mapList.push({isMap:true,title:"Bangladesh",swf:"FCMap_Bangladesh.swf",width:460,height:620});
	mapList.push({isMap:true,title:"Bhutan",swf:"FCMap_Bhutan.swf",width:790,height:450});
	mapList.push({isMap:true,title:"Brunei",swf:"FCMap_Brunei.swf",width:530,height:450});
	mapList.push({isMap:true,title:"Burma",swf:"FCMap_Burma.swf",width:600,height:1200});
	mapList.push({isMap:true,title:"Cambodia",swf:"FCMap_Cambodia.swf",width:430,height:360});
	mapList.push({isMap:true,title:"China",swf:"FCMap_China.swf",width:500,height:420});
	mapList.push({isMap:true,title:"China (With Direct-controlled municipalities and Special administrative regions)",swf:"FCMap_China2.swf",width:890,height:730});
	mapList.push({isMap:true,title:"Asia Georgia",swf:"FCMap_AsiaGeorgia.swf",width:580,height:300});
	mapList.push({isMap:true,title:"East Timor",swf:"FCMap_EastTimor.swf",width:1070,height:470});
	mapList.push({isMap:true,title:"Hong Kong",swf:"FCMap_HongKong.swf",width:760,height:600});
	mapList.push({isMap:true,title:"India",swf:"FCMap_India.swf",width:625,height:650});
	mapList.push({isMap:true,title:"Indonesia",swf:"FCMap_Indonesia.swf",width:800,height:300});
	mapList.push({isMap:true,title:"Japan",swf:"FCMap_Japan.swf",width:575,height:625});
	mapList.push({isMap:true,title:"Kazakhstan",swf:"FCMap_Kazakhstan.swf",width:570,height:420});
	mapList.push({isMap:true,title:"Laos",swf:"FCMap_Laos.swf",width:280,height:320});
	mapList.push({isMap:true,title:"Macau",swf:"FCMap_Macau.swf",width:490,height:780});
	mapList.push({isMap:true,title:"Malaysia",swf:"FCMap_Malaysia.swf",width:600,height:275});
	mapList.push({isMap:true,title:"Mongolia",swf:"FCMap_Mongolia.swf",width:830,height:430});
	mapList.push({isMap:true,title:"Nepal",swf:"FCMap_Nepal.swf",width:760,height:410});
	mapList.push({isMap:true,title:"North Korea",swf:"FCMap_NorthKorea.swf",width:530,height:560});
	mapList.push({isMap:true,title:"Philippines",swf:"FCMap_Philippines.swf",width:590,height:790});
	mapList.push({isMap:true,title:"Russia",swf:"FCMap_Russia.swf",width:675,height:450});
	mapList.push({isMap:true,title:"Singapore",swf:"FCMap_Singapore.swf",width:570,height:350});
	mapList.push({isMap:true,title:"South Korea",swf:"FCMap_SouthKorea.swf",width:550,height:570});
	mapList.push({isMap:true,title:"SriLanka",swf:"FCMap_SriLanka.swf",width:610,height:1050});
	mapList.push({isMap:true,title:"Taiwan",swf:"FCMap_Taiwan.swf",width:450,height:560});
	mapList.push({isMap:true,title:"Thailand",swf:"FCMap_Thailand.swf",width:710,height:1200});
	mapList.push({isMap:true,title:"Tibet",swf:"FCMap_Tibet.swf",width:510,height:340});
	mapList.push({isMap:true,title:"Vietnam",swf:"FCMap_Vietnam.swf",width:330,height:620});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"----------- Middle East -----------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"Afghanistan",swf:"FCMap_Afghanistan.swf",width:620,height:480});
	mapList.push({isMap:true,title:"Bahrain",swf:"FCMap_Bahrain.swf",width:160,height:230});
	mapList.push({isMap:true,title:"Iran",swf:"FCMap_Iran.swf",width:430,height:400});
	mapList.push({isMap:true,title:"Iraq",swf:"FCMap_Iraq.swf",width:320,height:330});
	mapList.push({isMap:true,title:"Israel",swf:"FCMap_Israel.swf",width:200,height:500});
	mapList.push({isMap:true,title:"Jordan",swf:"FCMap_Jordan.swf",width:530,height:590});
	mapList.push({isMap:true,title:"Kuwait",swf:"FCMap_Kuwait.swf",width:530,height:510});
	mapList.push({isMap:true,title:"Kyrgyzstan",swf:"FCMap_Kyrgyzstan.swf",width:770,height:400});
	mapList.push({isMap:true,title:"Lebanon",swf:"FCMap_Lebanon.swf",width:330,height:420});
	mapList.push({isMap:true,title:"Oman",swf:"FCMap_Oman.swf",width:460,height:580});
	mapList.push({isMap:true,title:"Pakistan",swf:"FCMap_Pakistan.swf",width:230,height:220});
	mapList.push({isMap:true,title:"Qatar",swf:"FCMap_Qatar.swf",width:230,height:440});
	mapList.push({isMap:true,title:"Saudi Arabia",swf:"FCMap_SaudiArabia.swf",width:430,height:380});
	mapList.push({isMap:true,title:"Syria",swf:"FCMap_Syria.swf",width:430,height:380});
	mapList.push({isMap:true,title:"Tajikistan",swf:"FCMap_Tajikistan.swf",width:330,height:250});
	mapList.push({isMap:true,title:"Turkmenistan",swf:"FCMap_Turkmenistan.swf",width:330,height:240});
	mapList.push({isMap:true,title:"United Arab Emirates",swf:"FCMap_UAE.swf",width:580,height:480});
	mapList.push({isMap:true,title:"Uzbekistan",swf:"FCMap_Uzbekistan.swf",width:400,height:240});
	mapList.push({isMap:true,title:"Yemen",swf:"FCMap_Yemen.swf",width:530,height:330});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"------------- Oceania -------------",swf:"",width:0,height:0});	
	mapList.push({isMap:true,title:"Australia",swf:"FCMap_Australia.swf",width:275,height:215});
	mapList.push({isMap:true,title:"Australia (W/Capital)",swf:"FCMap_Australia2.swf",width:660,height:610});
	mapList.push({isMap:true,title:"Fiji",swf:"FCMap_Fiji.swf",width:610,height:600});
	mapList.push({isMap:true,title:"Kiribati",swf:"FCMap_Kiribati.swf",width:330,height:170});
	mapList.push({isMap:true,title:"Marshall Islands",swf:"FCMap_MarshallIsland.swf",width:380,height:310});
	mapList.push({isMap:true,title:"Micronesia",swf:"FCMap_Micronesia.swf",width:760,height:340});
	mapList.push({isMap:true,title:"Nauru",swf:"FCMap_Nauru.swf",width:510,height:520});
	mapList.push({isMap:true,title:"New Caledonia",swf:"FCMap_NewCaledonia.swf",width:560,height:440});
	mapList.push({isMap:true,title:"New Zealand",swf:"FCMap_NewZealand.swf",width:410,height:600});
	mapList.push({isMap:true,title:"Palau",swf:"FCMap_Palau.swf",width:640,height:720});
	mapList.push({isMap:true,title:"Papua New Guinea",swf:"FCMap_PapuaNewGuinea.swf",width:810,height:570});
	mapList.push({isMap:true,title:"Samoa",swf:"FCMap_Samoa.swf",width:810,height:400});
	mapList.push({isMap:true,title:"Solomon Islands",swf:"FCMap_SolomonIsland.swf",width:590,height:280});
	mapList.push({isMap:true,title:"Tonga",swf:"FCMap_Tonga.swf",width:210,height:540});
	mapList.push({isMap:true,title:"Tuvalu",swf:"FCMap_Tuvalu.swf",width:360,height:390});
	mapList.push({isMap:true,title:"Vanuatu",swf:"FCMap_Vanuatu.swf",width:210,height:390});
	
	mapList.push({isMap:false,title:"  ",swf:"",width:0,height:0});
	mapList.push({isMap:false,title:"-------- Africa & Countries -------",swf:"",width:0,height:0});
	mapList.push({isMap:true,title:"Algeria",swf:"FCMap_Algeria.swf",width:330,height:320});
	mapList.push({isMap:true,title:"Angola",swf:"FCMap_Angola.swf",width:330,height:370});
	mapList.push({isMap:true,title:"Benin",swf:"FCMap_Benin.swf",width:170,height:290});
	mapList.push({isMap:true,title:"Botswana",swf:"FCMap_Botswana.swf",width:600,height:580});
	mapList.push({isMap:true,title:"Burkina Faso",swf:"FCMap_BurkinaFaso.swf",width:610,height:470});
	mapList.push({isMap:true,title:"Burundi",swf:"FCMap_Burundi.swf",width:460,height:500});
	mapList.push({isMap:true,title:"Cameroon",swf:"FCMap_Cameroon.swf",width:450,height:600});
	mapList.push({isMap:true,title:"Cape Verde",swf:"FCMap_CapeVerde.swf",width:710,height:630});
	mapList.push({isMap:true,title:"Central African Republic",swf:"FCMap_CentralAfricanRepublic.swf",width:460,height:320});
	mapList.push({isMap:true,title:"Chad",swf:"FCMap_Chad.swf",width:330,height:500});
	mapList.push({isMap:true,title:"Comoros",swf:"FCMap_Comoros.swf",width:620,height:550});
	mapList.push({isMap:true,title:"Congo",swf:"FCMap_Congo.swf",width:330,height:380});
	mapList.push({isMap:true,title:"Cote Divoire",swf:"FCMap_CoteDivoire.swf",width:520,height:570});
	mapList.push({isMap:true,title:"Democratic Republic of the Congo",swf:"FCMap_DemocraticRepublicofCongo.swf",width:430,height:430});
	mapList.push({isMap:true,title:"Djibouti",swf:"FCMap_Djibouti.swf",width:380,height:450});
	mapList.push({isMap:true,title:"Egypt",swf:"FCMap_Egypt.swf",width:410,height:420});
	mapList.push({isMap:true,title:"Equatorial Guinea",swf:"FCMap_EquatorialGuinea.swf",width:330,height:210});
	mapList.push({isMap:true,title:"Eritrea",swf:"FCMap_Eritrea.swf",width:430,height:390});
	mapList.push({isMap:true,title:"Ethiopia",swf:"FCMap_Ethiopia.swf",width:520,height:410});
	mapList.push({isMap:true,title:"Gabon",swf:"FCMap_Gabon.swf",width:320,height:350});
	mapList.push({isMap:true,title:"Gambia",swf:"FCMap_Gambia.swf",width:660,height:200});
	mapList.push({isMap:true,title:"Ghana",swf:"FCMap_Ghana.swf",width:600,height:690});
	mapList.push({isMap:true,title:"Guinea",swf:"FCMap_Guinea.swf",width:420,height:350});
	mapList.push({isMap:true,title:"Guinea-Bissau",swf:"FCMap_GuineaBissau.swf",width:690,height:430});
	mapList.push({isMap:true,title:"Kenya",swf:"FCMap_Kenya.swf",width:300,height:340});
	mapList.push({isMap:true,title:"Lesotho",swf:"FCMap_Lesotho.swf",width:620,height:540});
	mapList.push({isMap:true,title:"Liberia",swf:"FCMap_Liberia.swf",width:440,height:450});
	mapList.push({isMap:true,title:"Libya",swf:"FCMap_Libya.swf",width:580,height:600});
	mapList.push({isMap:true,title:"Madagascar",swf:"FCMap_Madagascar.swf",width:230,height:420});
	mapList.push({isMap:true,title:"Madagascar (Regions)",swf:"FCMap_MadagascarRegions.swf",width:380,height:630});
	mapList.push({isMap:true,title:"Malawi",swf:"FCMap_Malawi.swf",width:280,height:620});
	mapList.push({isMap:true,title:"Mali",swf:"FCMap_Mali.swf",width:480,height:480});
	mapList.push({isMap:true,title:"Mauritania",swf:"FCMap_Mauritania.swf",width:330,height:360});
	mapList.push({isMap:true,title:"Mauritius",swf:"FCMap_Mauritius.swf",width:330,height:360});
	mapList.push({isMap:true,title:"Morocco",swf:"FCMap_Morocco.swf",width:400,height:410});
	mapList.push({isMap:true,title:"Mozambique",swf:"FCMap_Mozambique.swf",width:310,height:510});
	mapList.push({isMap:true,title:"Namibia",swf:"FCMap_Namibia.swf",width:330,height:340});
	mapList.push({isMap:true,title:"Niger",swf:"FCMap_Niger.swf",width:570,height:460});
	mapList.push({isMap:true,title:"Nigeria",swf:"FCMap_Nigeria.swf",width:430,height:390});
	mapList.push({isMap:true,title:"Rwanda",swf:"FCMap_Rwanda.swf",width:480,height:430});
	mapList.push({isMap:true,title:"Sao Tome and Principe",swf:"FCMap_SaoTomeandPrincipe.swf",width:270,height:380});
	mapList.push({isMap:true,title:"Senegal",swf:"FCMap_Senegal.swf",width:620,height:450});
	mapList.push({isMap:true,title:"Seychelles",swf:"FCMap_Seychelles.swf",width:270,height:320});
	mapList.push({isMap:true,title:"Sierra Leone",swf:"FCMap_SierraLeone.swf",width:490,height:500});
	mapList.push({isMap:true,title:"Somalia",swf:"FCMap_Somalia.swf",width:460,height:620});
	mapList.push({isMap:true,title:"South Africa",swf:"FCMap_SouthAfrica.swf",width:460,height:500});
	mapList.push({isMap:true,title:"Sudan",swf:"FCMap_Sudan.swf",width:610,height:770});
	mapList.push({isMap:true,title:"Sudan(W/o South Sudan)",swf:"FCMap_SudanWoSouthSudan.swf",width:675,height:600});
	mapList.push({isMap:true,title:"South Sudan",swf:"FCMap_SouthSudan.swf",width:700,height:515});
	mapList.push({isMap:true,title:"Swaziland",swf:"FCMap_Swaziland.swf",width:180,height:220});
	mapList.push({isMap:true,title:"Tanzania",swf:"FCMap_Tanzania.swf",width:570,height:580});
	mapList.push({isMap:true,title:"Togo",swf:"FCMap_Togo.swf",width:180,height:400});
	mapList.push({isMap:true,title:"Tunisia",swf:"FCMap_Tunisia.swf",width:370,height:630});	
	mapList.push({isMap:true,title:"Uganda",swf:"FCMap_Uganda.swf",width:880,height:910});
	mapList.push({isMap:true,title:"Western Sahara",swf:"FCMap_WesternSahara.swf",width:340,height:310});
	mapList.push({isMap:true,title:"Zambia",swf:"FCMap_Zambia.swf",width:510,height:440});
	mapList.push({isMap:true,title:"Zimbabwe",swf:"FCMap_Zimbabwe.swf",width:500,height:470});

	return mapList;
}