/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version fusioncharts/3.3.1-release.19520
*/
FusionCharts(["private","modules.renderer.js-gradientlegend",function(){function S(c,d,e){var a=c[0],g=c[1],c=c[2];a+=(d[0]-a)*e;g+=(d[1]-g)*e;d=c+(d[2]-c)*e;return{hex:(B+(a<<16|g<<8|d).toString(16)).slice(-6),rgb:[a,g,d]}}function k(c,d){return c.maxvalue-d.maxvalue}function P(c){var d=c.colorRange||{},e=c.dataMin,a=c.dataMax,g=c.sortLegend||!1,i=c.mapByCategory||!1,j=c.defaultColor,s=c.numberFormatter,h=d.color,c=this.colorArr=[],f,u,E,b,t;this.mapByCategory=i;if(d.mapbypercent==="1")this.mapbypercent=
!0;if(d.gradient==="1"&&!i){this.gradient=!0;f=z($(d.startcolor,d.mincolor,d.code));g=N(z($(f,j,"CCCCCC")));i=this.scaleMin=J(d.startvalue,d.minvalue,this.mapbypercent?0:e);c.push({code:f,maxvalue:i,label:X(d.startlabel),codeRGB:N(f)});if(h&&(u=h.length))for(e=0;e<u;e+=1)j=h[e],f=z($(j.color,j.code)),b=J(j.value,j.maxvalue),t=J(j.minvalue),b>i&&c.push({code:f,maxvalue:b,userminvalue:t,label:X($(j.label,j.displayvalue)),codeRGB:N(f)});c.sort(k);u=c.length;for(e=1;e<u;e+=1)j=c[e],f=j.maxvalue-i,f>0?
(j.minvalue=i,j.range=f,i=j.maxvalue):(c.splice(e,1),e-=1,u-=1);if(c.length>=2)this.scaleMax=i,c[e-1].label=$(d.endlabel,c[e-1].label,c[e-1].displayvalue);if(c.length===1)b=J(d.maxvalue,this.mapbypercent?100:a),c.push({minvalue:i,maxvalue:b,range:b-i,label:d.endlabel}),this.scaleMax=b,delete c[0].code;d=c[0];a=c[c.length-1];if(!d.code||!a.code){u=ja(g);u={minRGB:ia((u[2]=0,u)),maxRGB:ia((u[2]=100,u))};if(!d.code)d.codeRGB=u.minRGB,d.code=ca(u.minRGB);if(!a.code)a.codeRGB=u.maxRGB,a.code=ca(u.maxRGB)}u=
c.length;for(e=1;e<u;e+=1)if(j=c[e],j.code){if(E){a=j;t=d.maxvalue;for(h=a.maxvalue-t;E<e;E+=1)g=c[E],f=S(d.codeRGB,a.codeRGB,(g.maxvalue-t)/h),g.code=f.hex,g.codeRGB=f.rgb}E=null;d=j}else E=E||e;if(this.scaleMin===void 0||this.scaleMax===void 0)this.noValidRange=!0}else if(h&&(u=h.length)){for(e=0;e<u;e+=1)j=h[e],f=$(j.color,j.code),b=J(j.maxvalue),t=J(j.minvalue),E=$(j.label,j.displayvalue,i?x:s.dataLabels(t)+" - "+s.dataLabels(b)),(f&&b>t||i&&E)&&c.push({code:f,maxvalue:b,minvalue:t,label:X(E),
labelId:E.toLowerCase()});c.length?g&&c.sort(k):this.noValidRange=!0}}function T(c,d){return d?l(c*100)/100+e:ba(c,x).toString()}var n=this.hcLib,a=window,a=/msie/i.test(navigator.userAgent)&&!a.opera,J=n.pluckNumber,B=n.COLOR_BLACK,g=n.COLOR_GLASS,U=n.FC_CONFIG_STRING,fa=n.graphics,ia=fa.HSBtoRGB,ja=fa.RGBtoHSB,ca=fa.RGBtoHex,N=fa.HEXtoRGB,o=n.COMMASTRING,x=n.BLANKSTRING,X=n.parseUnsafeString,ga=n.graphics.convertColor,pa=n.POSITION_TOP,Y=n.POSITION_MIDDLE,ka=n.POSITION_START,na=n.POSITION_END,sa=
n.graphics.getDarkColor,la=n.graphics.getLightColor,$=n.pluck,ba=n.getValidValue,ha=n.toRaphaelColor,l=Math.round,A=Math.max,m=Math.min,c=Math.abs,e="%",d="rgba(192,192,192,"+(a?0.0020:1.0E-6)+")",z=function(c){return c&&c.replace(/^#?([a-f0-9]+)/ig,"$1")};P.prototype={getColorObj:function(c){var d=this.colorArr,e=this.gradient?1:0,a=d[e];if(this.mapByCategory){for(c=X(c).toLowerCase();a;){if(a.labelId===c)return{code:a.code,seriesIndex:e};e+=1;a=d[e]}return{outOfRange:!0}}else if(this.gradient)if(this.scaleMin<=
c&&this.scaleMax>=c){for(;a&&a.maxvalue<c;)e+=1,a=d[e];c=(c-a.minvalue)/a.range;return{code:S(d[e-1].codeRGB,a.codeRGB,c).hex}}else return{outOfRange:!0};else{for(;a;){if(a.maxvalue>c&&a.minvalue<=c)return{code:a.code,seriesIndex:e};e+=1;a=d[e]}if((a=d[e-1])&&a.maxvalue===c)return{code:a.code,seriesIndex:e-1};return{outOfRange:!0}}}};P.prototype.constructor=P;n.colorRange=P;var j=n.configureGradientLegendOptions=function(c,d){var e=c.legend,a=d.chart;e.legendSliderBorderWidth=J(a.legendpointerborderthickness,
1);e.legendSliderBorderColor=ga($(a.legendpointerbordercolor,B),J(a.legendpointerborderalpha,100));e.legendSliderWidth=J(a.legendpointerwidth,a.legendpointerswidth,12);e.legendSliderHeight=J(a.legendpointerheight,a.legendpointersheight,12);e.legendColorBoxBorderColor=e.borderColor;e.legendColorBoxBorderWidth=e.borderWidth;e.legendScaleColor=ga($(a.legendscalelinecolor,B),J(a.legendscalelinealpha,100));e.legendScalePadding=J(a.legendscalepadding,4);e.legendScaleLineThickness=J(a.legendscalelinethickness,
1);e.legendScaleTickDistance=J(a.legendscaletickdistance,6);e.itemStyle.cursor="default";e.interActivity=J(a.interactivelegend,1)};n.placeGLegendBlockRight=function(c,d,e,a,g){n.configureLegendOptions(c,d.chart,!0,g,e);j(c,d);var g=c[U].smartLabel,i=c.legend,z,s,h=i.textPadding=2,f=h*2,u=i.title.padding,E=0,b=0,t=2*i.padding,d=J(d.chart.legendpadding,7)+i.borderWidth/2+1,O=c.colorRange||{},y=O.colorArr,da=O.mapbypercent,D=O.scaleMin,V=O.scaleMax-D,v=i.legendSliderWidth,w=i.legendSliderHeight/2,K=
i.legendScalePadding,F=i.legendScaleTickDistance;s=i.itemStyle||{};var p=J(parseInt(s.lineHeight,10)||12),r=p*0.75,M=e-t,k,o,oa=0,l,ta,H,I,B,Q;a-=t;if(!O.noValidRange&&y&&(o=y.length)>1){o-=1;if(i.title.text!==x)g.setStyle(i.title.style),b=g.getSmartText(i.title.text,M,A(p,a/4)),i.title.text=b.text,E=b.width+t,a-=b=b.height+u;M-=F+K+v;i.colorBoxX=v;u=A(p,M/2);M=m(M-u-4,p);l=A(p,a/2);k=a/4;g.setStyle(s);p=y[0];p.scaleLabel=T(p.maxvalue,da);z=g.getSmartText(p.label,k,M);p.label=z.text;K=z.height;p.labelY=
r-z.height/2;s=g.getSmartText(p.scaleLabel,u,l);p.scaleLabel=s.text;F=s.height/2;O=s.width;p.scaleLabelY=r-s.height/2;i.colorBoxY=A(F,z.width+f,w)+b;p=Q=y[o];p.scaleLabel=T(p.maxvalue,da);z=g.getSmartText(p.label,k,M);p.label=z.text;K=A(K,z.height);p.labelY=r-z.height/2;s=g.getSmartText(p.scaleLabel,u,l);p.scaleLabel=s.text;O=A(O,s.width);k=s.height/2;w=A(z.width+f,k,w);p.scaleLabelY=r-s.height/2;i.colorBoxHeight=w=a-i.colorBoxY-w;l=w-k;ta=w/V;I=m(w-oa,l-F)-4;for(k=1;k<o;k+=1)p=y[k],H=(p.maxvalue-
D)*ta,z=g.getSmartText(p.label,m(H-oa,w-H)*2,M),p.label=z.text,K=A(K,z.height),p.labelY=r-z.height/2,z=z.width/2,p.scaleLabel=T(p.maxvalue,da),s=g.getSmartText(p.scaleLabel,u,m(H-F,l-H)*2),p.scaleLabel=s.text,O=A(O,s.width),B=s.height/2,p.scaleLabelY=r-s.height/2,I=m(I,(H-A(B+F,z+oa)-4)*V/p.range),oa=z+H,F=B+H;I=A(m(I,(m(l-F,w-oa)-4)*V/Q.range,a*0.3),0);i.colorBoxHeight-=I;i.colorBoxWidth=K&&K+f||15;i.height=i.totalHeight=a+b+t-I;i.width=(O&&O+h)+i.colorBoxWidth+v+i.legendScaleTickDistance+i.legendScalePadding+
t;if(i.width<E)i.colorBoxX+=(E-i.width)/2,i.width=E;if(i.width>e)i.width=e;d+=i.width;c.chart.marginRight+=d;return d}else return i.enabled=!1,0};n.placeGLegendBlockBottom=function(c,d,e,a,g){n.configureLegendOptions(c,d.chart,!1,g,e);j(c,d);var g=c[U].smartLabel,i=c.legend,z,s,h=i.textPadding=2,f=i.title.padding,u=0,E=0,b=2*i.padding,d=J(d.chart.legendpadding,7)+i.borderWidth/2+1,t=c.colorRange||{},O=t.colorArr,y=t.mapbypercent,da=t.scaleMin,D=t.scaleMax-da,V=i.legendSliderWidth,v=i.legendSliderHeight,
w=i.legendScalePadding,K=i.legendScaleTickDistance,F=i.itemStyle||{},p=J(parseInt(F.lineHeight,10)||12),r=p*0.75,M=a-b,k,l,o,L=0,ta,H,I;e-=b;if(!t.noValidRange&&O&&(l=O.length)>1){l-=1;if(i.title.text!==x)g.setStyle(i.title.style),E=g.getSmartText(i.title.text,e,M/3),i.title.text=E.text,u=E.width+b,M-=E=E.height+f;M-=K+w+v;f=A(p,M/2);p=m(M-f-4,p);g.setStyle(F);k=e/4;o=k*2;t=O[0];t.scaleLabel=T(t.maxvalue,y);z=g.getSmartText(t.label,k,p);t.label=z.text;F=z.height;t.labelY=r-z.height/2;s=g.getSmartText(t.scaleLabel,
o,f);t.scaleLabel=s.text;M=s.width/2;w=s.height;if(!t.code)t.code=$(i.minColor,"CCCCCC");i.colorBoxX=A(M,z.width+h,V);t=K=O[l];t.scaleLabel=T(t.maxvalue,y);z=g.getSmartText(t.label,k,p);t.label=z.text;F=A(F,z.height);t.labelY=r-z.height/2;s=g.getSmartText(t.scaleLabel,o,f);t.scaleLabel=s.text;w=A(w,s.height);t=s.width/2;V=A(z.width+h,t,V);i.colorBoxWidth=V=e-i.colorBoxX-V;o=V-t;ta=V/D;I=m(V-L,o-M)-4;for(k=1;k<l;k+=1)t=O[k],H=(t.maxvalue-da)*ta,z=g.getSmartText(t.label,m(H-L,V-H)*2,p),t.label=z.text,
F=A(F,z.height),t.labelY=r-z.height/2,z=z.width/2,t.scaleLabel=T(t.maxvalue,y),s=g.getSmartText(t.scaleLabel,m(H-M,o-H)*2,f),t.scaleLabel=s.text,w=A(w,s.height),s=s.width/2,I=m(I,(H-A(s+M,z+L)-4)*D/t.range),L=z+H,M=s+H;I=A(m(I,(m(o-M,V-L)-4)*D/K.range,e*0.3),0);i.colorBoxWidth-=I;i.width=e+b-I;if(i.width<u)i.colorBoxX+=(u-i.width)/2,i.width=u;i.colorBoxY=E+v;i.colorBoxHeight=F&&F+2*h||15;i.height=i.totalHeight=(w&&w+h)+i.colorBoxHeight+E+v+i.legendScaleTickDistance+i.legendScalePadding+b;if(i.height>
a)i.height=a;d+=i.height;c.chart.marginBottom+=d;return d}else return i.enabled=!1,0};var M=function(){return{point:this}};n.rendererRoot.drawGradientLegendItem=function(e){var a=this,j=a.paper,z=a.options,k=a.canvasLeft,i=a.canvasTop,m=a.canvasWidth,s=a.canvasHeight,h=z.colorRange,f,u,E,b,t=z.legend,O=J(t.padding,4),y=t.itemStyle;parseInt(y.fontSize,10);var z=t.symbolStyle,da=t.interActivity,D=e.elements,e=D.elementGroup,V=t.layout==="vertical",v,w,K,F,p,r,ua=0,A=t.lighting3d,xa,oa,L=t.colorBoxX,
n=t.colorBoxY,H=xa=t.colorBoxWidth,I=oa=t.colorBoxHeight,S={FCcolor:{color:x,alpha:x,angle:0,ratio:x}},Q=S.FCcolor;L+=O;n+=O;var ea,W,Da=t.legendColorBoxBorderColor,ya=t.legendColorBoxBorderWidth,ma=["M"],T=t.legendScaleColor;r=t.legendScalePadding;var ba=t.legendScaleLineThickness,P=ba%2/2;u=t.legendScaleTickDistance;O=t.legendSliderWidth;t=t.legendSliderHeight;p=I/2;b=H/2;var N=O/2,Z=t/2,X,aa,U;W=0;var va=la("ABABAB",50),wa=sa("ABABAB",70),za=ga("ABABAB",100),wa=ga(wa,100),va=ga(va,100),Aa,R={isFirst:!0},
G={},ca,fa,ia,ja;if(h&&(f=h.colorArr)&&(E=f.length)>1){R.toolText=ca=K=h.scaleMin;G.toolText=fa=h=h.scaleMax;F=h-K;R.snapPX=G.snapPX=0;R.tooltipConstraint=G.tooltipConstraint="chart";R.getLabelConfig=G.getLabelConfig=M;R.tooltipPos=[0,0];G.tooltipPos=[0,0];G.tooltipOffsetReference=R.tooltipOffsetReference={};G.tooltipOffsetReference.left=R.tooltipOffsetReference.left+=k-20;G.tooltipOffsetReference.top=R.tooltipOffsetReference.top+=i;ia=D.colorBox=j.group("colorBox",e);if(V){R.tooltipPos[0]=G.tooltipPos[0]=
m+k;W=270;Q.angle=90;k=L-O;m=L+H;i=n-Z;v=n+Z;k=l(L-O)+0.5;m=l(L)+0.5;i=l(n-Z)+0.5;v=l(n+Z)+0.5;X=l(L+H)+0.5;U=l(n-2)+0.5;w=l(n+2)+0.5;ea=l(n)+0.5;s=L-N/2;aa=l(s-Z)+0.5;s=l(s)+0.5;p=n-Z/2;Z=l(p+Z)+0.5;p=l(p)+0.5;xa/=2;N=["M",k,i,"L",m,i,m,U,X,ea,m,w,m,v,k,v,"Z","M",aa,p,"L",s,p,"M",aa,ea,"L",s,ea,"M",aa,Z,"L",s,Z];Z=["M",k+1,i,"L",k+1,v,"M",aa,p-1,"L",s,p-1,"M",aa,ea-1,"L",s,ea-1,"M",aa,Z-1,"L",s,Z-1];p=L+H+r;v=l(p+u)+P;p=l(p)+P;ea=L+b;aa=E-1;for(u=0;u<E;u+=1)b=f[u],m=(b.maxvalue-K)/F,w=I*m+n,r=l(w)+
P,u?(Q.ratio+=o,Q.color+=o,Q.alpha+=o,ma.push("L",p,r,v,r,"M",p,r),u===aa?(s=na,r=w+2):(s=Y,r=w)):(ma.push(p,r,"L",v,r,"M",p,r),s=ka,r=w-2),Q.ratio+=(m-ua)*100,Q.color+=$(b.code,B),Q.alpha+=$(b.alpha,100),ua=m,b.legendItem=j.text(e).attr({text:b.label,x:ea,y:r,"text-anchor":s,"vertical-align":Y}).rotate(W,ea,r).css(y),b.legendSymbol=j.text(e).attr({text:b.scaleLabel,x:v,y:w,"text-anchor":ka,"vertical-align":Y}).css(y);R.xMin=G.xMin=0;R.xMax=G.xMax=0;R.yMin=G.yMin=0;R.yMax=G.yMax=I;R.x=G.x=0;R.y=0;
G.y=I}else{R.tooltipPos[1]=G.tooltipPos[1]=s+i;k=l(L-N)+0.5;m=l(L+N)+0.5;i=l(n-t)+0.5;v=l(n+I)+0.5;X=l(L-2)+0.5;s=l(L+2)+0.5;aa=l(L)+0.5;U=l(n)+0.5;w=n-Z/2;ea=l(w-Z)+0.5;w=l(w)+0.5;W=L-N/2;b=l(W+N)+0.5;W=l(W)+0.5;oa/=2;N=["M",k,i,"L",m,i,m,U,s,U,aa,v,X,U,k,U,"Z","M",W,ea,"L",W,w,"M",aa,ea,"L",aa,w,"M",b,ea,"L",b,w];Z=["M",k,i+1,"L",m,i+1,"M",W-1,ea,"L",W-1,w,"M",aa-1,ea,"L",aa-1,w,"M",b-1,ea,"L",b-1,w];r=n+I+r;W=l(r+u)+P;r=l(r)+P;w=n+p;aa=E-1;for(u=0;u<E;u+=1)b=f[u],m=(b.maxvalue-K)/F,v=H*m+L,p=l(v)+
P,u?(Q.ratio+=o,Q.color+=o,Q.alpha+=o,ma.push("L",p,r,p,W,"M",p,r),u===aa?(s=ka,p=v+2):(s=Y,p=v)):(ma.push(p,r,"L",p,W,"M",p,r),s=na,p=v-2),Q.ratio+=(m-ua)*100,Q.color+=$(b.code,B),Q.alpha+=$(b.alpha,100),ua=m,b.legendItem=j.text(e).attr({text:b.label,x:p,y:w,"text-anchor":s,"vertical-align":Y}).css(y),b.legendSymbol=j.text(e).attr({text:b.scaleLabel,x:v,y:W,"text-anchor":Y,"vertical-align":pa}).css(y);R.xMin=G.xMin=0;R.xMax=G.xMax=H;R.yMin=G.yMin=0;R.yMax=G.yMax=0;R.y=G.y=0;R.x=0;G.x=H}D.colorBox=
j.rect(ia).attr({x:L,y:n,width:H,height:I,fill:ha(S),stroke:Da,strokeWidth:ya});if(A)D.colorBoxEffect=j.rect(ia).attr({x:L,y:n,width:xa,height:oa,fill:g,"stroke-width":0});D.scale=j.path(e).attr({path:ma,stroke:T,"stroke-width":ba});Aa=function(b,h,f,c,d){var e;V?(e=h*F/I+K,c=h>0?c:c+h+0.01):(e=b*F/H+K,f=b>0?f:f+b+0.01);b=l(e*100)/100;d?(D.slider1.translate(f,c),D.slider1Effect.translate(f,c),D.slider1Tracker.toFront().translate(f,c).tooltip(b,null,null,!0),ca=e):(D.slider2.translate(f,c),D.slider2Effect.translate(f,
c),D.slider2Tracker.toFront().translate(f,c).tooltip(b,null,null,!0),fa=e);da&&(ja=clearTimeout(ja),ja=setTimeout(function(){a.setScaleRange&&a.setScaleRange(ca,fa)},100))};sliderDragging=function(b,h){var f,d=f=0,e,u=this.isFirst,a=u?G:R;if(V){d=this._startY+h;d<=0&&(d=0);d>I&&(d=I);if(u?d>a.y:d<a.y)d=a.y;if(c(d-this.y)>=(this.snapPX||0))e=!0}else{f=this._startX+b;f<=0&&(f=0);f>H&&(f=H);if(u?f>a.x:f<a.x)f=a.x;if(c(f-this.x)>=(this.snapPX||0))e=!0}if(e)Aa(f,d,f-this.x,d-this.y,u),this.x=f,this.y=
d};sliderDragStart=function(){this._startX=this.x;this._startY=this.y};sliderDragEnd=function(){};f=l(K*100)/100;D.slider1=j.path(e).attr({path:N,fill:za,strokeWidth:1,stroke:wa});D.slider1Effect=j.path(e).attr({path:Z,fill:"none",strokeWidth:1,stroke:va});D.slider1Tracker=j.rect(e).attr({ishot:!0,width:O,height:t+I,x:k,y:i,fill:d,stroke:"none"}).drag(sliderDragging,sliderDragStart,sliderDragEnd,R,R,R).tooltip(f,null,null,!0).css(z);f=l(h*100)/100;D.slider2=j.path(e).attr({path:N,fill:za,strokeWidth:1,
stroke:wa}).translate(G.x,G.y);D.slider2Effect=j.path(e).attr({path:Z,fill:"none",strokeWidth:1,stroke:va}).translate(G.x,G.y);D.slider2Tracker=j.rect(e).attr({ishot:!0,width:O,height:t+I,x:k,y:i,fill:d,stroke:"none"}).translate(G.x,G.y).css(z).drag(sliderDragging,sliderDragStart,sliderDragEnd,G,G,G).tooltip(f,null,null,!0)}}}]);
FusionCharts(["private","modules.renderer.js-annotations",function(){var S=this.core,k=this.hcLib,P=window,T=/msie/i.test(navigator.userAgent)&&!P.opera,n=k.addEvent,a=k.removeEvent,J=(P=k.hasTouch)?6:5,B="rgba(192,192,192,"+(T?0.0020:1.0E-6)+")",T=Math,g=T.min,U=T.max,fa=T.sin,ia=T.cos,ja=T.PI,ca=ja/180,N=this.extend,o=k.pluck,x=k.pluckNumber,X=k.graphics.convertColor,ga=k.getValidValue,pa=k.parseUnsafeString,Y=k.setImageDisplayMode,ka=k.graphics.parseColor,na=k.setLineHeight,sa={style:{}},la=k.toRaphaelColor,
$=function(c,e){return{start:-e,end:-c,angle:c-e}},ba=function(c,e,d,a){var j=0,g=0,e=e===void 0||e===null?1:e,q;if(!c||!c.toString)return d;c=c.toLowerCase().replace(/\s/g,"");if(d=c.match(/^[\+\-]?\d+(\.\d+)?|[\+\-]\d+(\.\d+)?/g)){for(q=0;q<d.length;q+=1)j+=Number(d[q])||0;j*=e}if(d=c.match(/^[\+\-]?(\$[a-z]+)|[\+\-](\$[a-z]+)/g))for(q=0;q<d.length;q+=1)g+=a[d[q]]||0;if(d=c.match(/^[\+\-]?\$\d+(\.\d+)?|[\+\-]\$\d+(\.\d+)?/g))for(q=0;q<d.length;q+=1)g=g+Number(d[q].replace("$",""))||0;return j+g},
ha=function(c){var e=this.__state.annotationGroupsById;(c=e&&e[c])&&c.wrapper&&c.wrapper.show()},l=function(c){var e=this.__state.annotationGroupsById;(c=e&&e[c])&&c.wrapper&&c.wrapper.hide()},A,m;A=function(c,e,d,a){this.options=c;this.chart=d;this.attrs={};this.css={};this.bounds={};this.shared=e;this.snaps=a||{};this.id=c.id||"";this.items=[];this.setup();this.scale()};N(A.prototype,{scaleImageX:1,scaleImageY:1,scaleText:1,scaleValue:1,scaleValueComplement:1,scaleX:1,scaleY:1});A.prototype.setup=
function(){var c=this.options;this.isBelow=o(c.showbelow,c.showbelowchart,this.shared.showbelow)!="0";this.useTracker=!this.isBelow&&this.chart.trackerGroup&&this.shared.useTracker};A.prototype.scale=function(){var c=this.options,e=this.chart,d=this.shared,a=this.bounds,g=this.snaps,k=d.rootxscale,q=d.rootyscale,m=a.xs=x(c.xscale,d.xscale,100)/100,l=a.ys=x(c.yscale,d.yscale,100)/100,n,C,i;this.scaleText*=l;this.scaleImageX*=m;this.scaleImageY*=l;if(o(c.autoscale,d.autoscale)!="0")m=x(c.origw,d.origw),
l=x(c.origh,d.origh),m=e.chartWidth/m,l=e.chartHeight/l,e=o(c.constrainedscale,d.constrainedscale)!="0",n=m<l?m:l,C=e?n:m,i=e?n:l,this.scaleValue*=n,this.scaleValueComplement*=e?n:m<l?l:m,this.scaleX*=C,this.scaleY=this.scaleX*i,a.xs*=C,a.ys*=i,k*=C,q*=i,o(c.scaletext,d.scaletext)=="1"&&(this.scaleText*=i),o(c.scaleimages,d.scaleimages)=="1"&&(this.scaleImageX*=C,this.scaleImageY*=i);a.x=ba(o(c.x,c.xpos),k,0,g)+x(c.grpxshift,d.grpxshift,0);a.y=ba(o(c.y,c.ypos),q,0,g)+x(c.grpyshift,d.grpyshift,0);
this.xshift=x(c.xshift,d.xshift,0);this.yshift=x(c.yshift,d.yshift,0)};A.prototype.draw=function(){var c=this.chart,e=this.options,d=this.bounds,a=this.items,g=c.layers.dataset,k=this.wrapper;if(!k)this.wrapper=k=c.paper.group("annotations"),g&&(this.isBelow?k.insertBefore(g):k.insertAfter(c.layers.datalabels||g));for(this.wrapper.attr({x:0,y:0,visibility:e.visible=="0"?"hidden":""}).translate(d.x,d.y);d=a.unshift();)d.remove();if(e=e.items){d=0;for(g=e.length;d<g;d+=1)a.push((new m(c,e[d],this)).draw())}return this};
A.prototype.destroy=function(){for(var c=this.wrapper,e=this.items,d;d=e.shift();)d.destroy();if(c)this.wrapper=c.remove()};m=function(c,e,d){var a=!1,g;this.chart=c;this.options=e;this.group=d;this.args=[];this.attrs={};this.attrsTracker={};this.style={};this.bounds={};this.type=e.type&&e.type.toLowerCase&&e.type.toLowerCase();for(g in m.eventNames)typeof e[g]==="function"&&(this[g]=e[g],a=!0);this.hasEvents=a;if(typeof e.onload==="function")this.onload=e.onload;this.scale();this.setup()};m.prototype.getAbsoluteBounds=
function(){var c=this.bounds,e=c.x1,d=c.y1,a=c.x2,j=c.y2,k=g(e,a),q=g(d,j),e=U(e,a)-k,d=U(d,j)-q;return{x:k,width:e,y:q,height:d,r:c.r,unscaled:{width:e/c.xs,height:d/c.ys}}};m.prototype.scale=function(){var c=this.group,e=c.bounds,d=this.bounds,a=this.options,g=c.snaps,k=o(a.x,a.xpos),q=o(a.y,a.ypos),m=o(a.tox,a.toxpos),l=o(a.toy,a.toypos),n=d.xs=e.xs,e=d.ys=e.ys,C=x(a.xshift,c.xshift,0),i=x(a.yshift,c.yshift,0);this.hasDimensionY=this.hasDimensionX=this.hasDimension=!0;d.x1=ba(k,n,0,g)+C;m===void 0?
(this.hasDimensionX=this.hasDimension=!1,d.x2=d.x1):d.x2=ba(m,n,0,g)+C;d.y1=ba(q,e,0,g)+i;l===void 0?(this.hasDimensionY=this.hasDimension=!1,d.y2=d.y1):d.y2=ba(l,e,0,g)+i;d.r=x(a.radius,0)*c.scaleValue};m.prototype.setup=function(){var c=this.options,a=this.group,d=a.options,g=this.attrs,j=this.style,k=a.scaleValue,q=x(d.fillalpha,d.alpha,100),m=this.fillAlpha=o(c.fillalpha,c.alpha,q),l=this.fillColor=o(c.fillcolor,c.color,d.color,"#ff0000"),n=this.fillPattern=o(c.fillpattern&&c.fillpattern.toLowerCase&&
c.fillpattern.toLowerCase(),d.fillpattern&&d.fillpattern.toLowerCase&&d.fillpattern.toLowerCase()),C=c.showborder?c.showborder=="1":ga(c.bordercolor),q=this.borderAlpha=x(c.borderalpha,c.alpha,d.borderalpha,q),i=this.dashed=c.dashed=="1";this.link=o(c.link,d.link);this.shadow=o(c.showshadow,d.showshadow)=="1";g.stroke=C?X(o(c.bordercolor,l),q):"none";g["stroke-linecap"]="round";this.fillOptions={gradientUnits:"objectBoundingBox",color:l,alpha:m,ratio:o(c.fillratio,d.fillratio),angle:360-x(c.fillangle,
0),radialGradient:n==="radial"};g["stroke-width"]=C?x(c.borderthickness,c.thickness,2)*k:0;i&&(g["stroke-dasharray"]=[x(c.dashlen,5)*k,x(c.dashgap,3)*k]);if(this.link)j.cursor="pointer",j._cursor="hand";this.useTracker=a.useTracker;this.toolText=pa(o(c.tooltext,d.tooltext));if(this.useTracker||this.link||this.toolText)N(this.attrsTracker,{stroke:B,fill:B}),this.link&&(this.attrsTracker.ishot=+new Date)};m.prototype.draw=function(){var c=this.chart,e=this.type,d=this.attrs,g=this.style,j=c.paper,k=
m.types[e]&&m.types[e].call&&m.types[e].call(this),q=k==="image",l=k==="text",o=q||l,x=this.link||this.toolText,C=this.wrapper,e=this.tracker,i=c.layers.tracker||this.group.wrapper,A=!1,s,h=m.eventNames,f,u;if(k){if(C)if(C.elemType!==k)C=C.remove();else if(this.hasEvents)for(f in h)if((u=this[f])&&u.eventAttached)a(s.node,h[f],u),u.eventAttached=!1;if(!q&&d.fill===void 0)d.fill=la(this.fillOptions);C?C.attr(d).css(g):(this.args.push(this.group.wrapper),C=this.wrapper=j[k].apply(j,this.args).attr(d).css(g),
C.elemType=k,A=!0,this.args.pop());this.shadow&&!this.shadowAdded&&!q&&!l?C.shadow(this.shadowAdded=!0,U(this.borderAlpha,this.fillOptions.alpha)/100):C.shadow(this.shadowAdded=!1);if(x){if(this.useTracker){if(!e)this.args.push(i),e=this.tracker=o?j.rect(0,0,0,0,0,i):j[k].apply(j,this.args),this.args.pop();e.attr(d).attr(this.attrsTracker)}}else e&&(e=e.remove());s=this.tracker||C;this.link&&s.click(c.linkClickFN,this);this.toolText&&s.tooltip(this.toolText||"");if(this.hasEvents)for(f in h)if((u=
this[f])&&!u.eventAttached)n(s.node,h[f],u,this),u.eventAttached=!0;q||(e&&o&&(c=C.getBBox(),e.attr({x:c.x,y:c.y,width:c.width,height:c.height})),A&&this.onload&&this.onload(d))}return this};m.prototype.destroy=function(){var c=this.wrapper;if(c)this.tracker&&this.tracker.remove(),this.wrapper=c.remove()};m.eventNames={onmouseover:P?"touchstart":"mouseover",onmouseout:"mouseout",onmousemove:P?"touchmove":"mousemove",onclick:"click"};m.textAlignOptions={left:"start",right:"end",center:"middle"};m.textVerticalAlignOptions=
{top:"bottom",middle:"middle",bottom:"top"};m.textRotationOptions={0:"0",1:"270",right:"90",left:"270"};m.types={rectangle:function(){var c=this.args,a=this.getAbsoluteBounds(),d=a.width*0.5;if(a.r>d)a.r=d;c[0]=a.x;c[1]=a.y;c[2]=a.width;c[3]=a.height;c[4]=a.r;return"rect"},line:function(){var c=this.options,a=this.group.scaleValue,d=this.attrs,g=this.bounds;this.args[0]=["M",g.x1,g.y1,"L",g.x2,g.y2];d.stroke=X(this.fillColor,this.fillAlpha);d["stroke-width"]=x(c.thickness,2)*a;d["stroke-width"]===
1&&(d["shape-rendering"]="crisp");d["stroke-width"]<J&&(this.attrsTracker["stroke-width"]=J);this.attrsTracker["stroke-dasharray"]="solid";return"path"},polygon:function(){var c=this.args,a=this.options,d=this.bounds;c[0]=x(a.sides,5);c[1]=d.x1;c[2]=d.y1;c[3]=d.r;c[4]=x(a.startangle,0);c[5]=0;return"polypath"},circle:function(){var c=this.args,a=this.options,d=this.bounds,g=this.chart.chartWidth,j=this.chart.chartHeight,k=this.group.scaleValueComplement,q=$(x(a.startangle,0),x(a.endangle,360)),m=
d.r,l;if(!o(a.radius))d.r=g<j?g*d.xs:j*d.ys,d.r=m=d.r*0.3;a=x(a.yradius,m/k)*k;if(!this.fillPattern)this.fillOptions.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern==="radial")this.fillOptions.cx=this.fillOptions.cy=0.5;if(!(q.angle%360)&&m===a)return c[0]=d.x1,c[1]=d.y1,c[2]=d.r,"circle";q.angle%360||(q.start-=0.0010);j=q.start*ca;g=q.end*ca;q=q.angle*ca;k=d.x1;l=d.y1;d=k+ia(j)*m;j=l+fa(j)*a;k+=ia(g)*m;g=l+fa(g)*a;c[0]=["M",d,j,"A",m,a,0,0,q>=ja?0:1,k,g,"Z"];return"path"},arc:function(){var c=
this.options,a=this.args,d=this.bounds,g=this.chart.chartWidth,j=this.chart.chartHeight,k=this.group.scaleValue,m=$(x(c.startangle,0),x(c.endangle,360));if(!o(c.radius))d.r=g<j?g*d.xs:j*d.ys,d.r*=0.3;d.innerR=x(c.innerradius,d.r*0.8/k)*k;if(d.innerR>d.r)d.innerR+=d.r,d.r=d.innerR-d.r,d.innerR-=d.r;if(!this.fillPattern)this.fillOptions.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern==="radial")this.fillOptions.cx=this.fillOptions.cy=0.5;a[0]=d.x1;a[1]=d.y1;a[2]=d.r;a[3]=d.innerR;a[4]=
m.start*ca;a[5]=m.end*ca;return"ringpath"},text:function(){var c=this.chart,a=this.args,d=this.style,g=this.attrs,j=this.group,k=this.bounds,q=this.options,l=this.getAbsoluteBounds(),n=o(q.align,j.options.textalign,"center").toLowerCase(),A=o(q.valign,j.options.textvalign,"middle").toLowerCase(),C=pa(o(q.text,q.label)),i=this.chart&&this.chart.logic&&this.chart.logic.smartLabel,B=o(q.wrap,j.options.wraptext)=="1",s,h,f=o(q.rotatetext,j.options.rotatetext,"0").toLowerCase(),f=m.textRotationOptions[f],
u=f!="0"?"y":"x",E=c.options.orphanStyles,c=N({},E.defaultStyle.style||{}),E=E[j.id.toLowerCase()]||sa,c=N(c,E.style),E=parseFloat(c.fontSize),b=o(q.font,j.options.font,c.fontFamily),j=x(q.fontsize,j.options.fontsize,E)*j.scaleText;B&&(s=x(q.wrapwidth,this.hasDimensionX?l.width/k.xs:void 0),h=x(q.wrapheight,this.hasDimensionY?l.height/k.ys:void 0),s&&(s*=k.xs),h&&(h*=k.ys));d.fontFamily=b;d.fontWeight=o(q.bold,q.isbold)=="1"?"bold":"normal";if(o(q.italic,q.isitalic)=="1")d.fontStyle="italic";q.bgcolor&&
(!g["text-bound"]&&(g["text-bound"]=[]),g["text-bound"][0]=ka(q.bgcolor));q.bordercolor&&(!g["text-bound"]&&(g["text-bound"]=[]),g["text-bound"][1]=ka(q.bordercolor),g["text-bound"][2]=x(q.borderthickness,1),g["text-bound"][3]=x(q.padding,1));if(q.fontcolor)g.fill=ka(q.fontcolor);d.fontSize=j+"px";j==E?d.lineHeight=c.lineHeight:na(d);g["text-anchor"]=m.textAlignOptions[n]||m.textAlignOptions.center;i.setStyle(d);d=i.getSmartText(C,s,h,!1);g["vertical-align"]=m.textVerticalAlignOptions[A]||m.textVerticalAlignOptions.middle;
g["text-anchor"]===m.textAlignOptions.left?l[u]+=x(q.leftmargin,0):g["text-anchor"]===m.textAlignOptions.center&&(l[u]+=x(q.leftmargin,0)*0.5);if(f!=="0")g.rotation=[parseFloat(f),l.x,l.y];a[0]=l.x;a[1]=l.y;a[2]=d.text;d.tooltext&&(g.title=d.tooltext);delete g.stroke;delete g["stroke-weight"];return"text"},image:function(){var c=this,a=c.chart,d=c.style,g=a.chartWidth,j=a.chartHeight,a=c.options,k=c.attrs,m=c.args,l=ga(a.url),n=c.group.scaleImageX*o(Number(a.xscale),100)/100,A=c.group.scaleImageY*
o(Number(a.yscale),100)/100,C=c.getAbsoluteBounds(),i={width:1,height:1},B;if(!l)return m[0]=C.x,m[1]=C.y,m[2]=C.width,m[3]=C.height,m[4]=C.r,"rect";B=new Image;B.onload=function(){i=Y("none","top","left",100,0,g,j,B);delete i.x;delete i.y;i=N(i,{width:(c.hasDimensionX?C.unscaled.width:i.width)*n,height:(c.hasDimensionY?C.unscaled.height:i.height)*A});setTimeout(function(){var a,h,f;if(a=c.wrapper){a.attr(i);if(h=c.tracker)f=a.getBBox(),h.attr({x:f.x,y:f.y,width:f.width,height:f.height});a.css({opacity:d.opacity=
U(x(c.fillAlpha,c.borderAlpha),c.borderAlpha)/100})}c.onload&&c.onload(i)},0)};B.src=l;m[0]=l;m[1]=C.x;m[2]=C.y;m[3]=(c.hasDimensionX?C.unscaled.width:i.width)*n;m[4]=(c.hasDimensionY?C.unscaled.height:i.height)*A;d.opacity=U(x(c.fillAlpha,c.borderAlpha),c.borderAlpha)/100;delete k.stroke;delete k.fill;delete k["stroke-linecap"];return"image"}};k.rendererRoot.callbacks.unshift(function(a){var g=a.chartInstance,d=g.__state,k=a.dataObj||{},j=k.annotations,m=a.hcJSON,l={},n,B;if(!a.drawAnnotations||
!g.dataReady()||!k.chart||!(k.chart.showannotations!="0"&&j&&j.groups&&j.groups.length)){if(!m||!m.annotations)return;j=m.annotations;if(j.options)l=j.options}else delete j.id;if(!d.annotationStores)d.annotationStores=[];d.annotationStores.push(g=j.id||"annotations");g=this[g]=[];l=N({showbelow:o(j.showbelow,j.showbelowchart),autoscale:j.autoscale,scaletext:j.scaletext,scaleimages:j.scaleimages,constrainedscale:j.constrainedscale,origw:o(j.origw,k.chart.origw,this.chartWidth),origh:o(j.origh,k.chart.origh,
this.chartHeight),xshift:j.xshift,yshift:j.yshift,grpxshift:j.grpxshift,grpyshift:j.grpyshift,xscale:j.xscale,yscale:j.yscale,rootxscale:x(j.xscale,100)/100,rootyscale:x(j.yscale,100)/100},l);if(a.snapLiterals){n=a.snapLiterals;a={};for(B in n)a["$"+B]=a["+$"+B]=n[B],a["-$"+B]=n[B]*-1;n=a}d.annotationGroupsById||(d.annotationGroupsById={});for(a=0;a<j.groups.length;a+=1)g.push(B=(new A(j.groups[a],l,this,n)).draw()),B.id&&d.annotationGroupsById&&!this.forExport&&(d.annotationGroupsById[B.id]&&d.annotationGroupsById[B.id].destroy(),
d.annotationGroupsById[B.id]=B)});S.addEventListener("rendered",function(a,g){if(g.renderer==="javascript"){var d=a.sender,k=d.jsVars||{},j=k.instanceAPI;if(!k.hcObj||!j||!j.drawAnnotations)delete d.showAnnotation,delete d.hideAnnotation;else{if(!d.showAnnotation)d.showAnnotation=d.ref.showAnnotation=ha;if(!d.hideAnnotation)d.hideAnnotation=d.ref.hideAnnotation=l}}});S.addEventListener("Initialized",function(a){var a=a.sender,g=a.__state;if(a.options.renderer==="javascript")g.annotationGroupsById=
{}});S.addEventListener("Disposed",function(a){if(a.sender.options.renderer==="javascript"){var g=a.sender,a=g.__state,g=g.jsVars.hcObj,d,k,j,m;for(m=a.annotationStores&&a.annotationStores.length||0;m--;){j=a.annotationStores[m];if(d=g&&g[j])for(;k=d.shift();)k.destroy();delete a[j]}}})}]);
FusionCharts(["private","modules.renderer.js-maps",function(){var S=this,k=S.hcLib,P,T=P=k.chartAPI,n=document,a=k.pluck,J=k.imprint,B=k.extend2,g=k.pluckNumber,U=k.pluckFontSize,fa=k.placeLegendBlockRight,ia=k.placeGLegendBlockRight,ja=k.placeGLegendBlockBottom,ca=k.placeLegendBlockBottom,N=k.HCstub,o=B(k.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",
backgroundlightalpha:"100",backgroundlightangle:90,backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),x=k.setLineHeight,X=k.getValidValue,ga=k.parseUnsafeString,pa=k.getFirstColor,Y=k.graphics.convertColor,ka=k.hashify,na=navigator.userAgent,sa=window,la=/msie/i.test(na)&&!sa.opera,$=/AppleWebKit/.test(na),ba=k.hasSVG,ha=k.FC_CONFIG_STRING,l=Math,A=l.min,m=l.max,c=l.ceil,
na=!/fusioncharts\.com$/i.test(location.hostname),e=k.toRaphaelColor,d=function(h,a){var c;h||(h={});for(c in a)h[c]=a[c];return h},z=function(h){var a=this.parentNode;if(!a)return!1;for(;a;)if(a===n.documentElement)break;else if(a===h)return!0;else a=a.parentNode;return!1},j=function(a,f){var c=!f?{FCcolor:a}:d(a.FCcolor,f);c.toString=e;return c},M=function(a,f){var c,d;this.index=f;for(d in a)c=o[a[d]],this[d]=c instanceof Array?c[f]:c},q={right:function(a,f){return f},left:function(a,f){return a-
f},center:function(a,f){return A(f,a-f)*2}},Ba={top:function(a,f){return f},middle:function(a,f){return A(f,a-f)*2},bottom:function(a,f){return a-f}},qa=function(){if(this.hoverEntity)k.raiseEvent.apply(k,this.hoverEntityEventArgs),delete this.hoverEntityEventArgs,this.hoverEntity&&this.hoverEntityAttr&&this.hoverEntity.attr(this.hoverEntityAttr),delete this.hoverEntityAttr,this.hoverEntity=null},Ca=function(a,f,c,d){function b(){var b=this,a=b.entityPathMap,h=b.data,f=h&&h.length||0,c=b.items,d,
g,u,t=function(){for(g=0;f--;){if(g++>50){t();break}d=h[f];u=d.id&&d.id.toLowerCase();var y=d;delete y.outlines;delete y.label;delete y.shortlabel;delete y.labelposition;delete y.labelalignment;delete y.labelconnectors;d=y;if(u!==void 0&&a[u])c[u]=h[f].mapItem=new C(u,J(d,a[u]),e,b.group)}};t();for(d in a)c[d]||(c[d]=new C(d,a[d],e,b.group))}function g(){var b=this.items,a=[],h,f;i.push({id:"entityLabels",items:a});for(f in b)(h=b[f].getLabelObject())&&a.push(h)}if(c=c&&c.getEntityPaths()){var e=
f,y=e.options,i;if(!y.annotations)y.annotations={id:"geo",showbelow:0,autoscale:0,grpxshift:e.translateX?e.translateX:0,grpyshift:e.translateY?e.translateY:0,xscale:(e.sFactor?e.sFactor:1)*100,yscale:(e.sFactor?e.sFactor:1)*100,options:{useTracker:!0},groups:[]};i=y.annotations.groups;this.entityPathMap=c;this.data=a;this.chartObj=e;this.items={};this.group=d||f.mapGroup;b.call(this);y.entities.labelsOnTop&&g.call(this);this.drawLabels=g;this.destroy=function(){var b=this.items,a;for(a in b)b[a].destroy();
delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group};this.init=b;if(!e.__canvasMouseOutListenerAdded){e.__canvasMouseOutListenerAdded=!0;var D=f.paper.canvas;k.addEvent(D,"mouseout",function(b){b=b.relatedTarget;!la||ba?(!b||!(b.ownerSVGElement&&b.ownerSVGElement===D))&&qa.call(e):b===n.documentElement||b===f.container||b===f.container.parentElement?qa.call(e):z.call(b,D)||qa.call(e)})}}},C=function(h,f,d,e){function b(){var b=this.chart.paper,a=ba||
!la?"litepath":"path",h=this.eJSON.outlines,f=this.group,c,g;c=h&&h.length||0;if(P)for(;c--;)g=h[c],this.svgElems[c]={},this.svgElems[c].graphic=b[a](g,f).attr(U).tooltip(K).shadow(X,d.shadowLayer);else for(;c--;)g=h[c],this.svgElems[c]={},this.svgElems[c].graphic=b[a](g,f).tooltip(K).attr(U);this.addMouseGestures();return this}function t(b){var a=this.svgElems[0].pointProxy;a!==this.chart.hoverPoint&&(qa.call(this.chart),i.call(this,a,b))}function i(b){var a=this.chart;a.hoverEntity=this;a.hoverEntityEventArgs=
["entityrollout",this.eventArgs,a.fusionCharts,[a.fusionCharts.id,"rollOut",this.legacyEventArgs],b];if(W&&this.isVisible)a.hoverEntityAttr=this.revertAttr,this.attr(this.hoverAttr);k.raiseEvent("entityrollover",this.eventArgs,a.fusionCharts,[a.fusionCharts.id,"rollOver",this.legacyEventArgs],b)}if(f&&d&&h!==void 0){this.chart=d;this.eJSON=f;this.group=e;this.id=h;this.originalId=f.origId;this.isVisible=!0;this.svgElems={};this.connectorElem={};var y=d.options,h=y.entities,da=h.dataLabels.style,e=
h.valuesForMarkers?null:f.cleanValue,D=e===null?void 0:e,V=a(f.displayvalue,h.includeNameInLabels?h.useShortName?f.shortLabel:f.label:""),e=this.formattedValue=f.formattedValue||"",v=h.labelSepChar,w=g(f.showtooltip,h.showTooltip),K=this.toolText=w?ga(a(f.tooltext,(h.useSNameInTooltip?f.shortLabel:f.label)+(isNaN(D)?"":h.tooltipSepChar+e))):"",F,p,r,s=g(f.showlabel,h.showLabels),n=a(f.bordercolor,h.borderColor),o=a(f.borderalpha,h.borderAlpha);r=h.scaleBorder===1;var x=g(f.borderthickness,h.borderThickness),
z=a(f.labelconnectorcolor,h.connectorColor),B=a(f.labelconnectoralpha,h.connectorAlpha),A=a(f.font,da.fontFamily),C=g(parseInt(f.fontsize,10),parseInt(da.fontSize,10)),J=a(f.fontcolor,da.color),Q=g(f.labelpadding,h.labelPadding),M=h.hoverOnEmpty,W=g(f.usehovercolor,M?h.useHoverColor:isNaN(D)?0:h.useHoverColor),N=g(f.hoverborderthickness,h.hoverBorderThickness),ya=g(f.fontbold,0),ma=f.link,P=h.shadow,w=!la||ba,da=d.sFactor/h.baseScaleFactor;F=d.strokeWidth;p=(w?h.baseScaleFactor:1)*F;var T=h.hiddenEntityFillObject||
(h.hiddenEntityFillObject={fill:j({color:h.hiddenEntityColor,alpha:h.hiddenEntityAlpha}).toString()}),U,X,y=y[ha],Z=y._labelBaseWidth,ca=y._labelBaseHeight,aa=y._labelXOffset,fa=y._labelYOffset;w?(x=r?x*p:x/da)&&$&&(x=c(x)):x=r?x*F:x;N=N===void 0?x:r?x*p:N/da;if(a(f.color,f.alpha,f.angle,f.ratio)!==void 0)w=a(f.color,h.fillColor),y=a(f.alpha,h.fillAlpha),F=a(f.angle,h.fillAngle),p=a(f.ratio,h.fillRatio),r=j({color:w,alpha:y,angle:F,ratio:p});else{if(!h.fillColorObject)h.fillColorObject=j({color:a(h.fillColor),
alpha:a(h.fillAlpha),angle:a(h.fillAngle),ratio:a(h.fillRatio)});if(!h.emptyColorObject)h.emptyColorObject=j({color:a(h.emptyEntityColor),alpha:a(h.emptyEntityAlpha),angle:a(h.emptyEntityAngle),ratio:a(h.emptyEntityRatio)});r=isNaN(D)?h.emptyColorObject:h.fillColorObject;w=r.FCcolor.color;y=r.FCcolor.alpha;F=r.FCcolor.angle;p=r.FCcolor.ratio}K===""&&(w=0);U={transform:ba||!la?"":d.transformStr,stroke:Y(n,o),"stroke-width":x,fill:(this.fillColor=r).toString()};n=y.split(",");x&&n.push(o);X={scalefactor:[da,
d.sFactor],opacity:m.apply(l,n)/100};if(W){if(a(f.hovercolor,f.hoveralpha,f.hoverangle,f.hoverratio)!==void 0)w=a(f.hoverfillcolor,f.hovercolor,h.hoverFillColor),y=a(f.hoverfillalpha,f.hoveralpha,h.hoverFillAlpha),F=a(f.hoverfillangle,f.hoverangle,h.hoverFillAngle),p=a(f.hoverfillratio,f.hoverratio,h.hoverFillRatio),o=j({color:w,alpha:y,angle:F,ratio:p});else{if(!h.hoverColorObject)h.hoverColorObject=j({color:h.hoverFillColor,alpha:h.hoverFillAlpha,angle:h.hoverFillAngle,ratio:h.hoverFillRatio});
o=h.hoverColorObject}this.hoverColor=o}!f.displayvalue&&h.includeValueInLabels&&!isNaN(D)&&(V=V===void 0?e:V+v+e);this.value=D;this.addMouseGestures=function(){var b=this,a=b.chart,h=b.eJSON,f=b.svgElems,c;b.eventArgs={value:b.value,label:h.label,shortLabel:h.shortLabel,originalId:b.originalId||b.id,id:b.id};b.legacyEventArgs={value:b.value,lName:h.label,sName:h.shortLabel,id:b.originalId||b.id};if(W)b.hoverAttr={"stroke-width":N,fill:b.hoverColor.toString()},b.revertAttr={"stroke-width":x,fill:b.fillColor.toString()};
if(!isNaN(D)||M)for(c in f)ma!==void 0&&f[c].graphic.css({cursor:"pointer",_cursor:"hand"}),f[c].graphic.node.__entity=b,f[c].graphic.click(function(a){S.raiseEvent("entityclicked",b.eventArgs,d.fusionCharts,a);ma!==void 0&&d.logic.linkClickFN.call({link:ma})}).hover(function(h){this.node.__entity!==a.hoverEntity&&(qa.call(b.chart),i.call(b,h))},function(){})};this.attr=function(b,a){var h=this.svgElems,f;for(f in h)h[f].graphic&&h[f].graphic.attr(b,a)};this.draw=b;this.getLabelObject=function(){var b=
this,a=b.eJSON,h=b.chart.paper,f=a.labelPosition,c=a.labelAlignment,a=a.labelConnectors,g=b.svgElems[0]&&b.svgElems[0].graphic,e,y;if(!s||!g||!V)return null;for(e=a&&a.length||0;e--;)y=a[e],b.connectorElem[e]=h.path(y,b.group).attr({stroke:Y(z,B),"stroke-width":x});f?(h=f[0],a=f[1]):(f=g.getBBox(),h=f.x+f.width/2,a=f.y+f.height/2);c?(f=c[0],c=c[1],f==="right"?h-=Q:f==="left"&&(h+=Q),c==="top"?a-=Q:c==="bottom"&&(a+=Q)):(f="center",c="middle");return{x:h.toString(),y:a.toString(),wrapwidth:q[f](Z,
h+aa)-Q,wrapheight:Ba[c](ca,a+fa)-Q,wrap:1,type:"text",align:f,valign:c,text:V,tooltext:b.toolText,link:ma,bgcolor:"",bordercolor:"",fontcolor:J,fontsize:parseFloat(C)/d.sFactor,font:A,bold:ya,onclick:function(a){S.raiseEvent("entityclicked",b.eventArgs,d.fusionCharts,a)},onmouseover:function(){t.apply(b,arguments)},ontouchstart:function(){t.apply(b,arguments)}}};this.destroy=function(){var b=this.svgElems,a=this.connectorElem,h;for(h in b)b[h].remove&&b[h].remove();for(h in a)a[h].destroy&&a[h].destroy();
delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options};this.show=function(){var b=this.svgElems,a;this.isVisible=!0;for(a in b)b[a].graphic&&b[a].graphic.attr(U)};this.hide=function(){var b=this.svgElems,a;this.isVisible=!1;for(a in b)b[a].graphic&&b[a].graphic.attr(T)};b.call(this);
h.hideEmptyEntities&&D===void 0&&this.hide()}},i=function(a,f,c){this.id=a;this.definition=f;this.application=null;this.rapi=c;if(a=c.options)this._conf=a[ha]},ra=function(a,f,c,d){this.options=a;this.from=f;this.to=c;this.api=d;if(a=d.options)this._conf=a[ha]},s=function(a,f,c,d){this.appliedMarkers={};this.shapeObjs={};this.items={};this.connectors=[];this.options=f;this.mJSON=a;this.rapi=c;this.group=c.paper.group(d);var a=c.options,b;if(!a.annotations)a.annotations={id:"geo",showbelow:0,autoscale:0,
grpxshift:a.chart.marginLeft?a.chart.marginLeft:0,grpyshift:a.chart.marginLeft?a.chart.marginTop:0,xscale:(c.sFactor?c.sFactor:1)*100,yscale:(c.sFactor?c.sFactor:1)*100,options:{useTracker:!0},groups:[]};b=a.annotations.groups;this.setDefaultValues=function(){var b=this.options,a=this.rapi,f=b.markers,b=b.connectors,h=i.prototype,c=ra.prototype;h.markerFont=f.dataLabels.style.fontFamily;h.markerFontSize=f.dataLabels.style.fontSize;h.markerFontColor=f.dataLabels.style.fontColor;h.showMarkerTooltip=
f.showTooltip;h.showMarkerLabels=f.showLabels;h.markerLabelPadding=f.labelPadding;h.labelWrapWidth=f.labelWrapWidth;h.labelWrapHeight=f.labelWrapHeight;h.labelSepChar=f.labelSepChar;h.tooltipSepChar=f.tooltipSepChar;h.fillColor=f.fillColor;h.fillAlpha=f.fillAlpha;h.fillRatio=f.fillRatio;h.fillAngle=f.fillAngle;h.startAngle=f.startAngle;h.shapeId=f.shapeId;h.borderThickness=f.borderThickness;h.borderColor=f.borderColor;h.borderAlpha=f.borderAlpha;h.markerRadius=f.radius;h.autoScale=f.autoScale?a.sFactor:
1;h.shadow=f.shadow;c.showTooltip=b.showTooltip;c.thickness=b.thickness;c.color=b.color;c.alpha=b.alpha;c.dashed=b.dashed;c.dashlen=b.dashLen;c.dashgap=b.dashGap;c.font=b.font;c.fontsize=b.fontSize;c.fontcolor=b.fontColor;c.bgcolor=b.labelBgColor;c.bordercolor=b.labelBorderColor;c.shadow=b.shadow};this.applyMarkers=function(){var a=this.mJSON.application,f=a&&a.length,h=[],c=[],d,g,e,u=this.items,i=this.appliedMarkers,k;b.push({id:"markers",fillalpha:"100",items:h});for(b.push({id:"markerlabels",
items:c});f;f-=1){d=null;e=a[f-1];k=e.id&&e.id.toLowerCase();if(e.mapItem=g=u[k]){if(e.shapeid)g.shapeObj=this.shapeObjs[e.shapeid.toLowerCase()];d=g.apply(e)}if(d)g._annotationIndex=h.length,i[k]=g,h.push(d.markerItem),d.markerLabel&&c.push(d.markerLabel)}d=null;if(this.options.markers.applyAll)for(f in u)if(!i[f]){if(g=u[f]){if(g.shapeid)g.shapeObj=this.shapeObjs[g.shapeid.toLowerCase()];d=g.apply(g)}if(d)g._annotationIndex=h.length,this.appliedMarkers[k]=g,h.push(d.markerItem),d.markerLabel&&c.push(d.markerLabel)}};
this.defineMarkersNShapes=function(){var b=this.mJSON.definition,a=this.mJSON.shapes,f,h,d;if(b&&b.length){if(a&&a.length)for(f=a.length;f;f-=1)if(h=a[f-1],d=h.id.toLowerCase())this.shapeObjs[d]=h;for(f=b.length;f;f-=1)if(h=b[f-1],d=h.id.toLowerCase()){a=new i(d,h,c);if(h.shapeid)a.shapeObj=this.shapeObjs[h.shapeid];this.items[d]=a}}};this.drawConnectors=function(){var a=this.options.connectors.showLabels,f=this.mJSON&&this.mJSON.connectors,h=f&&f.length,c=[],d=[],g,e,u;if(h){b.push({id:"connectors",
fillalpha:"100",items:c});for(b.push({id:"connectorLabels",fillalpha:"100",items:d});h--;)if(u=f[h],g=this.items[u.from.toLowerCase()],e=this.items[u.to.toLowerCase()],e=new ra(u,g,e,this.rapi),g=e.computeConnectorJSON())c.push(g),g.label&&a&&d.push(e.getLabelJSON)}};this.destroy=function(){for(var b=this.items,a=b&&b.length||0;a--;)b[a].destroy();delete this.items;delete this.appliedMarkers;delete this.shapeObjs;delete this.connectors;delete this.options;delete this.chart;this.group.destroy();delete this.group};
this.setDefaultValues();this.defineMarkersNShapes();this.drawConnectors();this.applyMarkers()};ra.prototype={computeConnectorJSON:function(){var h=this.api,f=this.options,c=this.from,d=this.to,b=f.link,e=f.label,i=g(f.showtooltip,this.showTooltip),k=i?f.tooltext:"",j=a(f.thickness,this.thickness),m=a(f.color,this.color),l=a(f.alpha,this.alpha),v=a(f.dashed,this.dashed),w=g(f.dashlen,this.dashlen),f=g(f.dashgap,this.dashgap),K;return!c||!d?null:(K={fromMarkerId:c.id,toMarkerId:d.id},B({type:"line"},
{x:c.definition.x,y:c.definition.y,tox:d.definition.x,toy:d.definition.y,dashed:v,dashlen:w,dashgap:f,link:b,tooltext:i?k:"",thickness:j,color:m,alpha:l,label:e,showshadow:this.shadow,onmouseover:function(b){S.raiseEvent("connectorrollover",K,h.chartInstance,b)},onmouseout:function(b){S.raiseEvent("connectorrollout",K,h.chartInstance,b)},onclick:function(b){S.raiseEvent("connectorclicked",K,h.chartInstance,b)}}))},getLabelJSON:function(){var a=this.connectJSON;return B({type:"text"},{x:((Number(a.x)+
Number(a.tox))/2).toString(),y:((Number(a.y)+Number(a.toy))/2).toString(),text:a.label,align:"center",valign:"middle",font:this.font,fontsize:this.fontsize,fontcolor:this.fontcolor,bgcolor:this.bgcolor,bordercolor:this.bordercolor,tooltext:this.tooltext})}};ra.prototype.constructor=ra;i.prototype={getMarkerOptions:function(){},getLabelAttrs:function(a,f,c,d,b){var g,e=a&&a.toLowerCase();this.getLabelAlignment[e]||(e="center");a=Number(c.x);g=Number(c.y);c=d===void 0||b===void 0?c.radius||0:/^(top|bottom)$/ig.test(e)&&
b*0.5||/^(left|right)$/ig.test(e)&&d*0.5||0;return this.getLabelAlignment[e](a,g,Number(c)+Number(f))},apply:function(h){h||(h={});var f=this.rapi,c=this._conf,d=f.translateX,b=f.translateY,e=this.definition,i=a(h.shapeid,e.shapeid),k=g(h.scale,e.scale,1),j=a(h.label,e.label)||"",m=a(h.labelpos,e.labelpos,"top").toLowerCase(),l=h.formattedValue===void 0?"":h.formattedValue,v=a(h.tooltext,e.tooltext)||(l?j+this.tooltipSepChar+l:j),w=g(h.radius,e.radius,this.markerRadius)*k*this.autoScale||1.0E-4;if(i){i=
i.toLowerCase();this.application=h;j=l?j+this.labelSepChar+l:j;isNaN(k)?k=1:k<0?k=0:k>5&&(k=5);options={x:e.x.toString(),y:e.y.toString(),fillcolor:a(h.fillcolor,h.color,this.fillColor),fillalpha:a(h.fillalpha,h.alpha,this.fillAlpha),fillratio:a(h.fillratio,this.fillRatio),fillangle:a(h.fillangle,this.fillAngle),borderthickness:g(h.borderthickness,this.borderThickness),bordercolor:a(h.bordercolor,this.borderColor),borderalpha:a(h.borderalpha,this.borderAlpha),radius:w,tooltext:this.showMarkerTooltip?
h.tooltext?h.tooltext:v:"",link:h.link,showshadow:g(h.showshadow,this.shadow),_markerLabel:j,_markerId:e.id,onmouseover:function(a){var h=a.data,c=h.options,h=h.bounds,g=c._markerRollOverArgs;if(!g)g=c._markerRollOverArgs={x:h.x1/h.xs,y:h.y1/h.ys,scaledX:h.x1,scaledY:h.y1,chartX:d+h.x1,chartY:b+h.y1,id:c._markerId,label:c._markerLabel};S.raiseEvent("markerrollover",g,f.chartInstance,a)},onmouseout:function(b){S.raiseEvent("markerrollout",b.data.options._markerRollOverArgs,f.chartInstance,b)},onclick:function(b){S.raiseEvent("markerclicked",
b.data.options._markerRollOverArgs,f.chartInstance,b)}};i==="triangle"?B(options,{type:"polygon",sides:3,startangle:this.startAngle}):i==="diamond"?B(options,{type:"polygon",sides:4,startangle:this.startAngle}):i==="arc"?B(options,{type:"arc",startangle:0,endangle:360,innerradius:w*0.6}):i==="circle"?options.type="circle":(e=this.getShapeArgs(),!e.radius&&(e.radius=this.markerRadius),e.radius*=k*this.autoScale,B(options,e));if(options.type==="image")options.borderthickness=h.borderthickness||0,options.onload=
function(b){var a=this.options,h=b.width,b=b.height,c=(Number(a.x)-h/(2*f.sFactor))*f.sFactor,a=(Number(a.y)-b/(2*f.sFactor))*f.sFactor,d;if(h&&b)for(d in{wrapper:1,tracker:1})this[d]&&this[d].attr({x:c,y:a,width:h,height:b})};if(!this.showMarkerLabels)return{markerItem:options};h=options.labelpadding||this.markerLabelPadding;m=this.getLabelAttrs(m,h,options);k=m.align;e=m.valign;l=c._labelBaseWidth;i=c._labelBaseHeight;v=c._labelXOffset;c=c._labelYOffset;l=this.labelWrapWidth?this.labelWrapWidth:
this.getWrapWidth[k](l,Number(m.x)+v);c=this.labelWrapHeight?this.labelWrapHeight:this.getWrapHeight[e](i,Number(m.y)+c);l>h&&(l-=h);c>h&&(c-=h);return{markerItem:options,markerLabel:B({type:"text"},{text:j,tooltext:options.tooltext,x:m.x,y:m.y,align:k,valign:m.valign,wrap:1,wrapwidth:l,wrapheight:c,fontsize:this.markerFontSize/f.sFactor,font:this.markerFont,fontcolor:this.markerFontColor})}}},setMarkerVisibility:function(a){var f=this.chart,f=f.options&&f.options.instanceAPI&&f.options.instanceAPI.chartInstance;
if(f=(f.__state&&f.__state.annotationGroupsById).markers.items[this._annotationIndex]){if(!this._origFill)this._origFill=j({alpha:f.fillAlpha,color:f.fillColor,angle:f.fillAngle,ratio:f.fillRatio}),this._hideFill=j({alpha:"0",color:f.fillColor,angle:f.fillAngle,ratio:f.fillRatio});a?f.wrapper.attr({fill:this._origFill}):f.wrapper.attr({fill:this._hideFill})}},getShapeArgs:function(){var a=this.shapeObj,f;if(a){if(a.type==="polygon")a.sides<3?a.type="circle":a.startangle=this.startAngle;else if(a.type===
"arc")f=(a.radius||this.markerRadius)*this.autoScale,a.radius=f,a.innerradius=a.innerradius&&a.innerradius*this.autoScale||f*0.6;return a}else return null},destroy:function(){},getLabelAlignment:{top:function(a,f,c){return{x:a.toString(),y:(f-c).toString(),align:"center",valign:"top"}},left:function(a,f,c){return{x:(a-c).toString(),y:f.toString(),align:"right",valign:"middle"}},right:function(a,f,c){return{x:(a+c).toString(),y:f.toString(),align:"left",valign:"middle"}},bottom:function(a,f,c){return{x:a.toString(),
y:(f+c).toString(),align:"center",valign:"bottom"}},center:function(a,f){return{x:a.toString(),y:f.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(a,f){return f},left:function(a,f){return a-f},center:function(a,f){return A(f,a-f)*2}},getWrapHeight:{top:function(a,f){return f},middle:function(a,f){return A(f,a-f)*2},bottom:function(a,f){return a-f}}};i.prototype.constructor=i;d(k.eventList,{entityrollover:"FC_Event",entityrollout:"FC_Event"});T("geo",{name:"(unknown)",revision:1,
creditLabel:na,standaloneInit:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",rendererId:"maps",entities:{},chart:function(c,f){B(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,chartbottommargin:this.dataObj.chart.mapbottommargin,chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var d=
this.dataObj,e=N(d,c,f,this),b=d.chart,i=e.chart,l=l=e[ha],y=i.useRoundEdges=g(b.useroundedges)===1,n=y?1:0,y=y?0:1,D=i.use3DLighting=g(b.use3dlighting,1)===1,s=B({},e.tooltip.style),v=new M(this.colorPaletteMap,(b.palette>0&&b.palette<6?b.palette:g(this.paletteIndex,1))-1),w=a(b.basefont,"Verdana"),q=U(b.basefontsize,10),o=a(b.basefontcolor,v.basefontcolor),p=U(b.outcnvbasefontsize,q),r=a(b.outcnvbasefont,w),z=p+"px",A=ka(a(b.outcnvbasefontcolor,o)),C=a(b.bgcolor,b.canvasbgcolor,v.canvasbgcolor),
J=a(b.bgalpha,b.canvasbgalpha,v.canvasbgalpha),L,P;q+="px";o=ka(o);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,e);i.events.click=this.linkClickFN;l.numberFormatter=this.numberFormatter;B(l,{width:c,height:f,showTooltip:g(b.showtooltip,this.showtooltip,1),tooltipSepChar:a(b.tooltipsepchar,", "),showValues:g(b.showvalues,this.showValues,1),showCanvasBG:a(b.showcanvasbg,1),useValuesForMarkers:g(b.usevaluesformarkers,0),outCanvasStyle:{fontFamily:r,color:A,fontSize:z},
inCanvasStyle:{fontFamily:w,fontSize:q,color:o}});L=x(l.outCanvasStyle);P=x(l.inCanvasStyle);l.trendStyle=l.outCanvasStyle;l.showCanvasBG=="0"&&(J="0");var H=a(b.bordercolor,v.plotbordercolor),I=a(b.fillcolor,v.plotfillcolor),S=a(b.fillalpha,v.plotfillalpha),Q=a(b.fillratio,v.plotfillratio),T=a(b.fillangle,v.plotfillangle),W=a(b.emptyentityfillcolor,b.emptyentitycolor,I);B(e,{chart:{emulateFlashGutter:g(b._emulateflashgutter,1),defaultSeriesType:this.defaultSeriesType,paletteIndex:v.index,borderRadius:g(b.canvasborderradius,
0),borderColor:Y(a(b.canvasbordercolor,v.canvasbordercolor),a(b.canvasborderalpha,v.canvasborderalpha)),borderWidth:g(b.showcanvasborder,y)?g(b.canvasborderthickness,1):0,backgroundColor:j({color:C,alpha:J,angle:a(b.bgangle,b.canvasbgangle,v.canvasbgangle),ratio:a(b.bgratio,b.canvasbgratio,v.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,plotBackgroundColor:j({color:"#ffffff",alpha:0}),bgSWF:a(b.bgimage,b.bgswf),bgSWFAlpha:g(b.bgimagealpha,b.bgswfalpha,100),bgImageScale:g(b.bgimagescale,
100),bgImageDisplayMode:a(b.bgimagedisplaymode,"none").toLowerCase(),logoURL:X(b.logourl),logoPosition:a(b.logoposition,"tl").toLowerCase(),logoAlpha:g(b.logoalpha,100),logoLink:X(b.logolink),logoScale:g(b.logoscale,100),logoLeftMargin:g(b.logoleftmargin,0),logoTopMargin:g(b.logotopmargin,0),toolbar:function(){var h;var d={button:{}},e=d.button,i;e.scale=g(b.toolbarbuttonscale,1.15);e.width=g(b.toolbarbuttonwidth,15);e.height=g(b.toolbarbuttonheight,15);e.radius=g(b.toolbarbuttonradius,2);e.spacing=
g(b.toolbarbuttonspacing,5);e.fill=Y(a(b.toolbarbuttoncolor,"ffffff"));e.labelFill=Y(a(b.toolbarlabelcolor,"cccccc"));e.symbolFill=Y(a(b.toolbarsymbolcolor,"ffffff"));e.hoverFill=Y(a(b.toolbarbuttonhovercolor,"ffffff"));e.stroke=Y(a(b.toolbarbuttonbordercolor,"bbbbbb"));e.symbolStroke=Y(a(b.toolbarsymbolbordercolor,"9a9a9a"));e.strokeWidth=g(b.toolbarbuttonborderthickness,1);e.symbolStrokeWidth=g(b.toolbarsymbolborderthickness,1);i=e.symbolPadding=g(b.toolbarsymbolpadding,5);e.symbolHPadding=g(b.toolbarsymbolhpadding,
i);e.symbolVPadding=g(b.toolbarsymbolvpadding,i);i=d.position=a(b.toolbarposition,"tr").toLowerCase();switch(i){case "tr":case "tl":case "br":case "bl":break;default:i="tr"}e=d.hAlign=(""+b.toolbarhalign).toLowerCase()==="left"?"l":i.charAt(1);h=d.vAlign=(""+b.toolbarvalign).toLowerCase()==="bottom"?"b":i.charAt(0),i=h;d.hDirection=g(b.toolbarhdirection,e==="r"?-1:1);d.vDirection=g(b.toolbarvdirection,i==="b"?-1:1);d.vMargin=g(b.toolbarvmargin,6);d.hMargin=g(b.toolbarhmargin,10);d.x=g(b.toolbarx,
e==="l"?0:c);d.y=g(b.toolbary,i==="t"?0:f);return d}()},title:{text:ga(b.caption),offsetX:Number(b.captionxshift),offsetY:Number(b.captionyshift),position:a(b.captionposition,b.captionxshift!==void 0||b.captionyshift!==void 0?"top left":"top"),padding:g(b.captionpadding,10),style:{fontFamily:r,color:A,fontSize:p+3+"px",fontWeight:g(b.captionfontbold)===0?"normal":"bold"}},subtitle:{text:ga(b.subcaption),style:{fontFamily:r,color:A,fontSize:p+1+"px",fontWeight:g(b.subcaptionfontbold)===0?"normal":
"bold"}},orphanStyles:{defaultStyle:{style:B({},l.inCanvasStyle)}},tooltip:{enabled:l.showTooltip!==0,style:{fontFamily:w,fontSize:q,lineHeight:P,color:o,padding:g(b.tooltippadding,this.tooltippadding,3)+"px",backgroundColor:Y(a(s.backgroundColor,b.tooltipbgcolor,v.tooltipbgcolor),a(b.tooltipbgalpha,"100")),borderColor:Y(a(s.borderColor,b.tooltipbordercolor,v.tooltipbordercolor),a(b.tooltipborderalpha,"100")),borderWidth:g(b.tooltipborderthickness,y)+"px",borderRadius:g(b.tooltipborderradius,n+1)+
"px"},constrain:g(b.constraintooltip,1),shadow:g(b.showtooltipshadow,b.showshadow,1)?{enabled:!0,opacity:m(g(b.tooltipbgalpha,100),g(b.tooltipborderalpha,100))/100}:!1},legend:{itemStyle:{fontFamily:r,fontSize:z,lineHeight:L,color:A},itemHiddenStyle:{fontFamily:r,fontSize:z,lineHeight:L},enabled:g(b.showlegend,1),title:{text:ga(b.legendcaption),style:{fontFamily:r,fontSize:z,lineHeight:L,color:A}},position:a(b.legendposition,g(d.colorrange&&d.colorrange.gradient,0)===0?"right":"bottom"),backgroundColor:a(b.legendbgcolor,
v.bgcolor),backgroundAlpha:a(b.legendbgalpha,"100"),borderColor:a(b.legendbordercolor,v.legendbordercolor),borderThickness:a(b.legendborderthickness,"1"),borderAlpha:a(b.legendborderalpha,"100"),shadow:g(b.legendshadow,1),allowDrag:g(b.legendallowdrag,0),scroll:{scrollBgColor:a(b.legendscrollbgcolor,"AAAAAA"),scrollBtnColor:a(b.legendscrollbtncolor,"BBBBBB"),scrollBarColor:a(b.legendscrollbarcolor,"CCCCCC")},reversed:g(b.reverselegend,0),interactive:g(b.interactivelegend,0),minColor:W,lighting3d:D},
markers:{dataLabels:{style:{fontFamily:a(b.markerfont,w),fontSize:g(b.markerfontsize,parseInt(q,10)),fontColor:a(b.markerfontcolor,o)}},showTooltip:g(b.showmarkertooltip,l.showTooltip),showLabels:g(b.showmarkerlabels,b.showlabels,1),labelPadding:a(b.markerlabelpadding,"5"),labelWrapWidth:g(b.markerlabelwrapwidth,0),labelWrapHeight:g(b.markerlabelwrapheight,0),fillColor:a(b.markerfillcolor,b.markerbgcolor,v.markerbgcolor),fillAlpha:a(b.markerfillalpha,v.markerbgalpha),fillAngle:a(b.markerfillangle,
v.markerbgangle),fillRatio:a(b.markerfillratio,v.markerbgratio),fillPattern:a(b.markerfillpattern,v.markerbgpattern),borderThickness:a(b.markerborderthickness,1),borderColor:a(b.markerbordercolor,v.markerbordercolor),borderAlpha:g(b.markerborderalpha,v.markerborderalpha),radius:g(b.markerradius&&k.trimString(b.markerradius),7),shapeId:a(b.defaultmarkershape,"circle"),labelSepChar:a(b.labelsepchar,", "),tooltipSepChar:l.tooltipSepChar,autoScale:g(b.autoscalemarkers,0),mapValueToRadius:g(b.mapmarkervaluetoradius,
0),startAngle:g(b.markerstartangle,90),maxRadius:g(b.maxmarkerradius,0.3*c),minRadius:g(b.minmarkerradius,0.02*c),applyAll:g(b.applyallmarkers,0),shadow:g(b.showmarkershadow,b.showshadow,0)},connectors:{thickness:g(b.connectorthickness,b.markerconnthickness,"2"),color:a(b.connectorcolor,b.markerconncolor,v.markerbordercolor),alpha:a(b.connectoralpha,b.markerconnalpha,"100"),dashed:g(b.connectordashed,b.markerconndashed,0),dashLen:g(b.connectordashlen,b.markerconndashlen,3),dashGap:g(b.connectordashgap,
b.markerconndashgap,2),font:a(b.connectorfont,b.markerconnfont,w),fontColor:a(b.connectorfontcolor,b.markerconnfontcolor,o),fontSize:g(b.connectorfontsize,b.markerconnfontsize,parseInt(q,10)),showLabels:g(b.showconnectorlabels,b.showmarkerlabels,b.showlabels,1),labelBgColor:a(b.connectorlabelbgcolor,b.markerconnlabelbgcolor,v.plotfillcolor),labelBorderColor:a(b.connectorlabelbordercolor,b.markerconnlabelbordercolor,v.markerbordercolor),shadow:g(b.showconnectorshadow,b.showmarkershadow,b.showshadow,
0),showTooltip:g(b.showconnectortooltip,b.showmarkertooltip,l.showTooltip)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:w,fontSize:q,lineHeight:P,color:e.plotOptions.series.dataLabels.color=o}},fillColor:I,fillAlpha:S,fillRatio:Q,fillAngle:T,borderColor:H,borderAlpha:a(b.borderalpha,this.borderAlpha,"100"),borderThickness:g(b.showborder,1)?g(b.borderthickness,1):0,scaleBorder:g(b.scaleborder,0),hoverFillColor:a(b.hoverfillcolor,b.hovercolor,v.plothoverfillcolor),hoverFillAlpha:a(b.hoverfillalpha,
b.hoveralpha,v.plothoverfillalpha),hoverFillRatio:a(b.hoverfillratio,b.hoverratio,v.plothoverfillratio),hoverFillAngle:a(b.hoverfillangle,b.hoverangle,v.plothoverfillangle),hoverBorderThickness:a(b.hoverborderthickness),emptyEntityColor:W,emptyEntityAlpha:a(b.emptyentityfillalpha,b.emptyentityalpha,S),emptyEntityRatio:a(b.emptyentityfillratio,b.emptyentityratio,Q),emptyEntityAngle:a(b.emptyentityfillangle,b.emptyentityangle,T),connectorColor:a(b.labelconnectorcolor,b.connectorcolor,o),connectorAlpha:a(b.labelconnectoralpha,
b.connectoralpha,"100"),useHoverColor:g(b.usehovercolor,1),hoverOnEmpty:g(b.hoveronempty,1),labelPadding:g(b.labelpadding,5),showLabels:g(b.showlabels,1),labelsOnTop:g(b.entitylabelsontop,1),includeNameInLabels:g(b.includenameinlabels,1),includeValueInLabels:g(b.includevalueinlabels,0),useSNameInTooltip:g(b.usesnameintooltip,0),useShortName:g(b.usesnameinlabels,1),labelSepChar:a(b.labelsepchar,", "),showTooltip:g(b.showentitytooltip,l.showTooltip),tooltipSepChar:l.tooltipSepChar,valuesForMarkers:g(b.usevaluesformarkers,
0),hideEmptyEntities:g(b.hideemptyentities,0),showHiddenEntityBorder:g(b.showhiddenentityborder,1),hiddenEntityColor:a(b.hiddenentitycolor,b.hiddenentityfillcolor,b.hiddenentityalpha||b.hiddenentityfillalpha?W:"ffffff"),hiddenEntityAlpha:a(b.hiddenentityalpha,b.hiddenentityfillalpha,0.0010),shadow:g(b.showshadow,this.defaultPlotShadow,v.shadow)},entitydef:{useSNameAsId:g(b.usesnameasid,0)}});if(b.tooltipcolor)e.tooltip.style.color=pa(b.tooltipcolor);if(a(b.clickurl)!==void 0)i.link=b.clickurl,i.style.cursor=
"pointer",la&&(i.style._cursor="hand"),e.plotOptions.series.point.events.click=function(){i.events.click.call({link:b.clickurl})};l=i.bgImageDisplayMode;n=X(b.bgimagevalign,"").toLowerCase();y=X(b.bgimagehalign,"").toLowerCase();l=="tile"||l=="fill"||l=="fit"?(n!="top"&&n!="middle"&&n!="bottom"&&(n="middle"),y!="left"&&y!="middle"&&y!="right"&&(y="middle")):(n!="top"&&n!="middle"&&n!="bottom"&&(n="top"),y!="left"&&y!="middle"&&y!="right"&&(y="left"));i.bgImageVAlign=n;i.bgImageHAlign=y;this.parseStyles(e);
x(e.title.style);x(e.subtitle.style);x(e.tooltip.style);e.plotOptions.series.allowPointSelect=!0;this.parseExportOptions(e);this.preSeriesAddition&&this.preSeriesAddition(e,d,c,f);this.series&&this.series(d,e,this.name,c,f);this.postSeriesAddition&&this.postSeriesAddition(e,d,c,f);this.spaceManager(e,d,c,f);window.console&&window.FC_DEV_ENVIRONMENT&&window.console.log(e);return e},series:function(c,f){var d=this.numberFormatter,e=this.hcJSON.series,b=this.dataObj,i=f[ha],j=b.colorrange,j=j&&j.color,
l=f.legend,n=i.useValuesForMarkers?b.markers&&b.markers.application||[]:b.data,D={},s=function(b){for(var a,c,d=q&&q.length||0;d--;)if(a=q[d],c=Number(a.maxvalue),a=g(a.minvalue,f.colorRange.scaleMin),b>=a&&b<=c)return d;return null},v=Infinity,w=-Infinity,o,q,p,r;l.type=b.colorrange&&b.colorrange.gradient==="1"?"gradient":"point";r=n&&n.length||0;for(i._doNotShowLegend=!0;r--;)o=n[r],p=o.value,o.cleanValue=d.getCleanValue(p),o.formattedValue=o.cleanValue!==null?d.dataLabels(p):void 0,o.origValue=
p,o.cleanValue!==null&&(v=A(o.cleanValue,v),w=m(o.cleanValue,w));v===Infinity&&(v=void 0);w===-Infinity&&(w=void 0);f.colorRange=new k.colorRange({colorRange:b.colorrange,dataMin:v,dataMax:w,defaultColor:l.minColor,numberFormatter:d});r=(q=f.colorRange.colorArr)&&q.length||0;if(r>0){for(;r--;){o=q[r];if(i._doNotShowLegend&&(o.label!==""||o.label!==void 0))i._doNotShowLegend=!1;e.push({type:this.defaultSeriesType,showInLegend:!0,data:[],plot:{},name:o.label,color:o.code,rangeMin:o.minvalue,rangeMax:o.maxvalue,
allVisible:!0,allHidden:!1,visible:!0,legendClick:function(){var b;if(b=this.chart)!this.legend&&(this.legend=this.plot.legend),b.legendClick(this,!this.visible)},setVisible:function(b){var a=this.data,c=this.legendItem,f=this.visible;this.visible=b=b===void 0?!f:b;c&&l.colorizeItem&&l.colorizeItem(this,b);for(f=a&&a.length;f--;)(c=a[f].mapItem)&&(c.setMarkerVisibility?c.setMarkerVisibility(b):b?c.show&&c.show():c.hide&&c.hide())}})}for(r=n&&n.length||0;r--;)if(o=n[r],b=s(g(o.value)),b!==null&&(d=
l.type==="gradient"?f.colorRange.getColorObj(o.value).code:j&&j[b]&&a(j[b].color,j[b].code),D[b]||(D[b]=[]),d))o.color=o.color?o.color:d,D[b].push(o);e=e.reverse();for(r in D)e[r]&&(e[r].data=D[r])}else e.push({type:this.defaultSeriesType,data:n||[]});i._doNotShowLegend&&(this.hcJSON.legend.enabled=!1)},spaceManager:function(a,c,d,e){var b=a.chart,g=a[ha];g.smartLabel=this.smartLabel;var i=b.spacingLeft,k=b.spacingTop,j=this.baseWidth,l=this.baseHeight;d-=b.spacingRight+i;b=e-(b.spacingBottom+k);
e=g._captionBlock=this.manageTitleSpace(a,c,d,b);c=g._legendBlock=this.placeLegendBlock(a,c,d,b-e.height,e.isBottom?e.height:0);a=d-c.width;c=b-e.height-c.height;g=j/l;d=a/(j*this.baseScaleFactor);b=c/(l*this.baseScaleFactor);d>b?(d=b,i+=(a-c*g)/2,j=200/(l*d)):(k+=(c-a/g)/2,j=200/(j*d));/bottom/i.test(e.position)||(k+=e.height);this.scaleFactor=d;this.strokeWidth=j;this.translateX=i;this.translateY=k},placeLegendBlock:function(a,c,d,e,b){var g=a.legend,i=a[ha],k=g.position.toLowerCase(),j={position:k};
if(c.chart.showlegend==="0"||i._doNotShowLegend)return j.height=0,j.width=0,j;if(k==="bottom"){if(j.height=g.type==="gradient"?ja(a,c,d,e):ca(a,c,d,e),j.width=0,b)g.y=-b}else d/=2,j.width=g.type==="gradient"?ia(a,c,d,e):fa(a,c,d,e),j.height=0;return j},manageTitleSpace:function(a,c,d,e){var b=this.hcJSON,a=b.title,c=b.chart,b=b.subtitle,g=this.smartLabel,i=e/2,k=0,j=a.position.toLowerCase(),l=a.padding,m=!1,o=a.offsetX,n=a.offsetY,q=0,s={},p,r;if(a.text===""&&b.text==="")return{height:0,position:j};
if(!isNaN(o)||!isNaN(n))m=!0,o=isNaN(o)?0:o,n=isNaN(n)?0:n;p=a.text;if(p!==""){g.setStyle(a.style);r=g.getOriSize(p);if(r.width>d||r.height>i)r=g.getSmartText(p,d,i),a.text=r.text,r.tooltext&&(a.originalText=r.tooltext);a.height=q=r.height;k+=q}i-=k;p=b.text;if(p!==""){g.setStyle(b.style);r=g.getOriSize(p);if(r.width>d||r.height>i)r=g.getSmartText(p,d,i),b.text=r.text,r.tooltext&&(b.originalText=r.tooltext);k+=b.height=r.height}k+l>i?k=i:k+=l;j.match(/left/)?(b.align=a.align="start",b.x=a.x=c.marginLeft):
j.match(/right/)?(b.align=a.align="end",b.x=a.x=d):(b.align=a.align="middle",b.x=a.x=d/2);/bottom/.test(j)?(d=e-k+c.marginTop+l,a.y=d,b.y=d+q,m?(a.y+=n,b.y+=n,a.x+=o,b.x+=o):(c.marginBottom+=k,s.isBottom=!0)):m?(a.y+=n,b.y+=n,a.x+=o,b.x+=o):c.marginTop+=k;s.height=m?0:k;s.position=j;return s},getEntityPaths:function(){return this.entities},redefineEntities:function(a,c){var d=this.entities,e={},b={},g,i,k,j,l,m,o,n;for(o=a.length;o--;)if(g=a[o],i=g.internalid,l=g.newid?g.newid:i,k=g.sname,g=g.lname,
(j=d[i])&&!(l!==i&&d[l])){e[l]=l={origId:i};b[i]=!0;for(m in j)l[m]=j[m];l.shortLabel=k?k:j.shortLabel;l.label=g?g:j.label}this.entities={};for(n in e)e[n].origId=n,this.entities[n.toLowerCase()]=e[n];for(n in d)if(!b[n])for(m in l=d[n],c.useSNameAsId?(this.entities[l.shortLabel.toLowerCase()]=j={},j.origId=l.shortLabel):(this.entities[n.toLowerCase()]=j={},j.origId=n),l)j[m]=l[m]},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",
bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",
tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerbgcolor:"backgrounddarkcolor",markerbgalpha:"backgrounddarkalpha",markerbgangle:"backgrounddarkangle",markerbgratio:"backgrounddarkratio",plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",
plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.hcObj.logic.name},getEntityList:function(){var a=this.jsVars.hcObj,a=a.entities&&a.entities.items,c=[void 0],d,e,b;for(d in a)e=a[d],b=e.eJSON,c.push({id:e.id,originalId:e.originalId||e.id,active:e.isVisible,lName:b.label,sName:b.shortLabel,
value:e.value,formattedValue:e.formattedValue,toolText:e.toolText});return c},getDataAsCSV:function(){var a=this.jsVars,a=a.hcObj&&a.hcObj.entities&&a.hcObj.entities.items,c='"Id","Short Name","Long Name","Value","Formatted Value"',d,e,b,g;for(d in a)e=a[d],b=e.eJSON,g=e.value,c+='\r\n"'+e.id+'","'+b.shortLabel+'","'+b.label+'","'+(g===void 0?"":g)+'","'+e.formattedValue+'"';return c},getMapAttribute:function(){var a=this.jsVars.hcObj.fusionCharts;S.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",
'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return a.getChartAttribute.apply(a,arguments)},exportMap:function(){var a=this.jsVars.hcObj.fusionCharts;S.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return a.exportChart&&a.exportChart.apply(a,arguments)}}},T.linebase);P("renderer.maps",{drawGraph:function(){var a=this.paper,c=this.layers,d,e,b;if(!this.options.nativeMessage){if(!c.dataset)c.dataset=
a.group("dataset").insertAfter(c.background),c.tracker=a.group("hot").insertAfter(c.dataset);if(!this.shadowLayer)this.shadowLayer=c.shadow=a.group("shadow").insertBefore(c.dataset);this.strokeWidth=this.logic.strokeWidth;d=this.logic.scaleFactor;this.translateX=e=this.logic.translateX;this.translateY=b=this.logic.translateY;this.sFactor=d*this.logic.baseScaleFactor;this.transformStr=["t",e,",",b,"s",d,",",d,",0,0"].join("");this.options.tooltip&&this.options.tooltip.enabled!==!1&&a.tooltip(this.options.tooltip.style,
this.options.tooltip.shadow,this.options.tooltip.constrain);this.processEntityDefs();this.drawEntities();if(!la||ba)c.dataset.attr({transform:this.transformStr}),c.shadow.attr({transform:this.transformStr});this.drawMarkers()}},setScaleRange:function(a,c){var f;for(var d=this.options,e=d[ha],b=e.useValuesForMarkers?this.markers:this.entities,g=b.items||b.appliedMarkers,e=e.useValuesForMarkers?{show:function(a){b.setMarkerVisibility(!0,a)},hide:function(a){b.setMarkerVisibility(!1,a)}}:{show:function(a){a.show()},
hide:function(a){a.hide()}},d=d.series,i=d.length,j,k,l,m;i--;)if(l=d[i],k=(j=l.data)&&j.length)if(l.rangeMin>=a&&l.rangeMax<=c){if(!l.allVisible)l.setVisible(!0),l.allVisible=!0}else if(l.rangeMax<a||l.rangeMin>c){if(!l.allHidden)l.setVisible(!1),l.allHidden=!0}else{l.allVisible=!1;for(l.allHidden=!1;k--;)l=j[k].id.toLowerCase(),f=(m=g[l])&&m.value,l=f,isNaN(l)||(l&&l>=a&&l<=c?e.show(m):e.hide(m))}},processEntityDefs:function(){var a=this.logic,c=this.options.series,d=c&&c.length;for(a.redefineEntities(a.dataObj.entitydef||
[],this.options.entitydef);d--;)c[d].chart=this},drawEntities:function(){var a=this.logic&&this.logic.dataObj&&this.logic.dataObj.data,c=this.layers.dataset,d=this.logic;this.eElems={};this.entities=new Ca(a,this,d,c)},drawMarkers:function(){var a=this.logic&&this.logic.dataObj||null;if(a=a&&a.markers||null)this.markerObjs=new s(a,{markers:this.options.markers,connectors:this.options.connectors},this,this.group);this.options.entities.labelsOnTop||this.entities.drawLabels()}},P["renderer.root"])},
[3,2,0,"release"]]);